<?PHP
session_start();
$_SESSION['idess']='';
$_SESSION['id_quality']='';
	/*
	Base Zend index file loaded for the index.php file
	*/

?>
<!--[if lt IE 7 ]><html dir="ltr" lang="en-US" class="no-js ie ie6 lte7 lte8 lte9"><![endif]-->
<!--[if IE 7 ]><html dir="ltr" lang="en-US" class="no-js ie ie7 lte7 lte8 lte9"><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="en-US" class="no-js ie ie8 lte8 lte9"><![endif]-->
<!--[if IE 9 ]>
<style type="text/css">
#search_top input{
margin-right:-3px;}
</style>
<![endif]-->

<script type="text/javascript">
function load_defect_search(){
$('#wo_container').css({display:'none'});
$('#WO_report').css({display:'none'});
$('#QA_report').css({display:'block'});
$('#qa_container').css({display:'block'});
}
function load_wo_search(){
$('#wo_container').css({display:'block'});
$('#WO_report').css({display:'block'});
$('#QA_report').css({display:'none'});
$('#qa_container').css({display:'none'});
}
</script>
<?php
$xml = $this->searchResult;
$titleDesc = array();
$desc = array();
$count_qa=0;$count_wo=0;$i=1;$wo=1; 
if(count($xml) > 0){
	foreach($xml as $key =>$val){
		if($key == 'result'){
			$result_found = $val['numFound'];
			$searchResult =  $val->doc;
			if(count($searchResult) > 0){
			foreach($searchResult as $k => $v){
					if(count($searchResult) > 0){
						foreach($searchResult as $sKey => $eVal){
						/* $comments='';
						for($i=0;$i<count($eVal->arr[1]->str);$i++)
						{$no = $i+1;
						$comments .= $no.'.'. $eVal->arr[1]->str[$i].'</br>';
						}*/
						$id[] =   $eVal->long[0];
						$project_id[] =  $eVal->str[1];
						$title[] = $eVal->str[2];
						$urllink[] =  $eVal->arr->str[1];
						$desc[] =  $eVal->str[4];
						$cat[] =  $eVal->str[5];
						/* $comment[] =  (array) $comments ;*/
						if( $eVal->str[5]=='quality'){
						$count_qa=$i++;
						if($count_qa==1){
						$id_quality.=$eVal->long[0];
						}else{$id_quality.=','.$eVal->long[0];}
						}
						else{$count_wo=$wo++;
						if($count_wo==1){
						$idess.=$eVal->long[0];
						}else{$idess.=','.$eVal->long[0];}}
						}
					}
				}

			}
		}

	}
}
$_SESSION['idess'] = $idess;
$_SESSION['id_quality'] = $id_quality;
if(strpos($_SERVER['HTTP_REFERER'],'quality')){
unset($_POST['search_par'][0]);
$_POST['search_par'][0]='Defect';
}

$pageURL = BASE_URL;
$search_text= str_replace('"', "", $this->search_text);
$search_text= str_replace("'", "",$search_text);
?>
<div class="title_med2 workorders_filter">
	<INPUT TYPE="hidden" ID="requestTypeFilter" VALUE="" />
	<?php if($result_found!=0){ ?>
		<label style="color: #fff;float: left; margin-top: 10px; font-size: 15px;" title="<?php echo $search_text;?>"><?php echo $result_found;?> Search results for "<?php echo ucfirst(substr(Util::escapewordquotes($search_text),0,70));if(strlen($search_text)>70){echo '...';} ?>"</label><?php } else{?>
		<label  style="color: #fff;float: left; margin-top: 10px; font-size: 15px;" >No result for "<?php echo ucfirst(substr(Util::escapewordquotes($search_text),0,70));if(strlen($search_text)>70){echo '...';} ?>" </label>
	<?php }?>
</div>
 <div class="search_wrapper_parent">
    <div class="search_select_radio">
     <?php if($result_found!=0){ ?> <ul>
        <li>
          <input name="Select Options" type="radio" class="radiobutton_wo" id="radio" value="radio" <?php if($_POST['search_par'][0]=='WorkO' && $count_wo!=0|| $_POST['search_par'][0]=='All' && $count_wo!=0){print  'checked="checked"'.' onclick="load_wo_search();"';}else{print  'onclick="load_wo_search();"';} ?>/>
          <label class="radiobutton_wo_text" >Work Orders (<?php echo $count_wo;?>) </label>
        </li>
        <li>
          <input name="Select Options" type="radio" class="radiobutton_qa" id="radio2" value="radio" <?php if($_POST['search_par'][0]=='All' && $count_qa!=0){print 'onclick="load_defect_search();"';}else if($_POST['search_par'][0]=='Defect' || $count_qa!=0) {print  'checked="checked"'.' '.'onclick="load_defect_search();"';} else{print 'onclick="load_defect_search();"';} ?> />
          <label class="radiobutton_qa_text">Defects (<?php echo $count_qa;?>) </label>
        </li>
      </ul>
    <?php if($_POST['search_par'][0]=='WorkO' || $_POST['search_par'][0]=='All'){?>
	  <button style="float:right; margin-top: 12px;margin-right: 28px;" id="WO_report" class="WO_report" onclick="return generateWOReport();"><span>Generate Report</span></button>
	  <button style="float:right; margin-top: 12px;margin-right: 28px;display:none;" id="QA_report" class="QA_report" onclick="return generateQAReport();"><span>Generate Report</span></button>
	   <?php } else {?><button style="float:right; margin-top: 12px;margin-right: 28px;" id="QA_report" class="QA_report" onclick="return generateQAReport();"><span>Generate Report</span></button><?php } ?>
    <?php } ?>
	
	<?php if($result_found == 0){ ?> <ul>
        <li>
          <input name="Select Options" type="radio" class="radiobutton_wo" id="radio" value="radio" disabled="disabled" checked="checked"/>
          <label class="radiobutton_wo_text" >Work Orders (0) </label>
        </li>
        <li>
          <input name="Select Options" type="radio" class="radiobutton_qa" id="radio2" value="radio" disabled="disabled"  />
          <label class="radiobutton_qa_text">Defects (0) </label>
        </li>
      </ul>
    
    <?php } ?>
	</div> <!-- END search_select_radio -->
  </div> <!-- END search_wrapper_parent -->
<?php if($result_found!=0){ ?> 
 <div id="wo_container" class="wo_container" <?php if($_POST['search_par'][0]=='Defect' || strpos($_SERVER['HTTP_REFERER'],'quality')){print 'style="display:none;"';}?>>
  <!--==| START: Bucket |==-->
		<?php 
		$cnt = 5;
			if($_SESSION['login_status'] == "client") {
				echo '<input type="hidden" name="client_login" id="client_login" value="client" />';
			} else {
				echo '<input type="hidden" name="client_login" id="client_login" value="employee" />';
			}
			$status_active = ($_REQUEST['status'] == '1') ? 'selected' : '';
			$status_archive = ($_REQUEST['status'] == '0') ? 'selected' : '';
			$status_draft = ($_REQUEST['status'] == '-1') ? 'selected' : '';
			echo '<!--=========== START: COLUMNS ===========-->
				<!--==| START: Bucket |==-->

				<div class="title_med workorders_filter">
					<label for="client_filter" id="client_filter_label">Client</label>
					<select id="client_filter" onchange="changeCompany();">
						<option value="-1">Show All</option>
					'.WoDisplay::getCompanyHTML().'
					</select>
					<label for="project_filter" id="project_filter_label">Project</label>
					<select id="project_filter" onchange="displayWorkorders(\'1\',\'first\',\'title\',\'1\',\'2\');">
						<option value="-1">Show All</option>
					</select>
					<label for="status_filter" id="status_filter_label">Status</label>
					<select id="status_filter" onchange="displayWorkorders(\'1\',\'first\',\'title\',\'1\');">
						<option value="-1" >Show All</option>
						'.WoDisplay::getAllStatusOptionHTML().'
						<option value="over_due">Over Due</option>
						<option value="99">Open</option>
					</select>
					<label for="assigned_filter" id="assigned_filter_label">Assigned To</label>
					<select id="assigned_filter" onchange="displayWorkorders(\'1\',\'first\',\'title\',\'1\',\'2\');">
						<option value="-1">Show All</option>
					</select>

					<label for="project_status_filter" id="project_status_filter_label">Type</label>
					<select id="project_status_filter" onchange="getWO_On_Status();"  style="width: 80px;">
					<option value="2" '.$status_active.'>Show All</option>
						<option value="1" '.$status_active.'>Active</option>
						<option value="0" '.$status_archive.'>Archived</option>
						<option value="-1" '.$status_draft.'>Draft</option>
					</select>
				</div>';
				$wo_data_cookie = isset($_COOKIE["lighthouse_wo_data"])? $_COOKIE["lighthouse_wo_data"] : "";
				$req_Type_Arr = Array();
				$req_Type_Arr['Outage'] = ' selected="selected"';
				$req_Type_Arr['Problem'] = ' selected="selected"';
				$req_Type_Arr['Request'] = ' selected="selected"';

				if(!empty($wo_data_cookie))
				{

					$wo_data_cookie_all = explode("~", @$wo_data_cookie);
					$requestTypeFilter = $wo_data_cookie_all[4];
					if(!empty($requestTypeFilter))
					{
						$req_Type_Arr = Array();
						$requestTypeFilter_all = explode(",", @$requestTypeFilter);
						for($u = 0; $u < sizeof($requestTypeFilter_all); $u++) {
							if(!empty($requestTypeFilter_all[$u]))
							{
								$req_Type_Arr[$requestTypeFilter_all[$u]] = ' selected="selected"';
							}
						}
					}
				}
				$end_date_default = date("m/d/Y");// current date;
				$start_date_add_one_month = strtotime(date("m/d/Y", strtotime($end_date_default)) . "-1 month");
				$start_date_default = date("m/d/Y", $start_date_add_one_month);
        echo '
				<INPUT TYPE="hidden" ID="start_date_hidden" VALUE="'.$start_date_default.'" />
				<INPUT TYPE="hidden" ID="end_date_hidden" VALUE="'.$end_date_default.'" />
				<INPUT TYPE="hidden" ID="search_hidden" VALUE="" />';

				echo '<div class="title_med2 workorders_filter">
				<INPUT TYPE="hidden" ID="requestTypeFilter" VALUE"" />
					<label for="project_status_filter" style="color: #fff;float: left; margin-top: 10px; font-size: 15px;" id="project_status_filter_label">Request Type</label>
					<select id="control_7" name="control_7[]" multiple="multiple" size="5">
						<option value=""></option>
						<option value="Outage" '.$req_Type_Arr['Outage'].'>Outage</option>
						<option value="Problem" '.$req_Type_Arr['Problem'].'>Problem</option>
						<option value="Request" '.$req_Type_Arr['Request'].'>Request</option>
				</select>';

				echo '<div class="title_med workorders_filter" style="position: inherit;align:center;">
				   <label style="padding-left:15px;" for="requestedby_filter" id="requestedby_filter_label">Request By</label>
					<select id="requestedby_filter" style="width: 140px;" onchange="displayWorkorders(\'1\',\'first\',\'title\',\'1\',\'2\');">
						<option value="-1">Show All</option>
					</select>
					 </div>
		
        </div>
				<!--==| END: Bucket |==-->
				
				<!--==| START: Sorting |==-->
				<ul class="project_filters workorders_sort">
					<li class="id"><a href="#" class="down" id="idsort" onClick="sortWorkorders(\'id\'); return false;">id</a></li>
					<li class="title"><a href="#" class="down" id="titlesort" onClick="sortWorkorders(\'title\'); return false;">title</a></li>
					<li class="req_type"><a id="req_typesort" href="#" onClick="sortWorkorders(\'req_type\'); return false;">Request Type</a></li>
			

                                        <li class="status"><a id="statussort" href="#" onClick="sortWorkorders(\'status\'); return false;">status</a></li>
					<li class="requested"><a id="requested_bysort" href="#" onClick="sortWorkorders(\'requested_by\'); return false;">requested by</a></li>
					<li class="assigned"><a id="assigned_tosort" href="#" onClick="sortWorkorders(\'assigned_to\'); return false;">assigned to</a></li>
					<li class="opendate"><a id="open_datesort" href="#" onClick="sortWorkorders(\'open_date\'); return false;">open date</a></li>
					<li class="due_date"><a id="due_datesort" href="#" onClick="sortWorkorders(\'due_date\'); return false;">due date</a></li>
					<li class="lastcommentby"><a id="lastcommentbysort" href="#" onClick="sortWorkorders(\'lastcommentby\'); return false;">last commented by</a></li>
					<li class="commentdate"><a id="commentdatesort" href="#" onClick="sortWorkorders(\'commentdate\'); return false;">commented date</a></li>
				</ul>

				<!--==| END: Sorting |==-->

				<!--==| START: Work Orders |==-->';
				$inStyle = '';
				$ua = $_SERVER['HTTP_USER_AGENT'];
				$checker = array(
				  'iphone'=>preg_match('/iPhone|iPod|iPad/', $ua),
				  'blackberry'=>preg_match('/BlackBerry/', $ua),
				  'android'=>preg_match('/Android/', $ua),
				);
			
				if ($checker['iphone'] || $checker['blackberry'] || $android['android']){
				//	  $inlineStyle = "style='height:auto;overflow:hidden'";
				 $inlineStyle = "style='background:none repeat scroll 0 0 #C9C9C9;clear:both;height:auto;overflow:hidden;padding: 0 3px 3px;position: relative;'";
		
						
				}
				echo '<input type="hidden" name="active_wo" id="active_wo" value="" />
				<div id="wo_containter" class="workorders_container" '.$inlineStyle.'>';
					
					echo '<!-- Company Break -->
				</div>
				<div style="display: none;" id="wo_dimmer_ajax" class="wo_save_box">
				<img alt="ajax-loader" src="/_images/ajax-loader.gif"/>
			</div>
				<!--==| END: Work Orders |==--></div>';
	
		
		
			?><div id="qa_container" class="qa_container" <?php if($_POST['search_par'][0]=='WorkO' || $_POST['search_par'][0]=='All' ){print 'style="display:none;"';}?>><!--=========== START: COLUMNS ===========-->
		

				<!--==| START: Bucket |==-->

				<?php echo '<div class="title_med workorders_filter">
					<label for="client_filter" id="client_filter_label">Client</label>
					<select id="client_filter" style="width:115px" onchange="changeCompany();">
						<option value="-1">Show All</option>
					'.QaDisplay::getCompanyHTML().'
					</select>
					<label for="qa_project_filter" id="qa_project_filter_label">Project</label>
					<select id="qa_project_filter" >
						<option value="-1">Show All</option>
					</select>

					<label for="status_filter" id="status_filter_label">Status</label>
					<select id="status_filter" >
						<option value="-1">Show All</option>
						<option value="99">Not Closed</option>
						'.QaDisplay::getAllStatusOptionHTML().'
					</select>
					<label for="project_severity_filter" id="project_status_filter_label">Severity</label>
					<select id="severity_filter" > 
						<option value="-1">Show All</option>
						'.QaDisplay::getcustomDropDown("QA_SEVERITY").'
					</select>
					<label for="qa_assigned_filter" id="qa_assigned_filter_label">Assigned To</label>
					<select id="qa_assigned_filter"  style="width:100px;">
						<option value="-1">Show All</option>
					</select>
					
					<a href="javascript:void(null);" onclick="qulaityFilterJson();"><img src="../_images/quality_refresh.png" alt="refresh" title="refresh" style="vertical-align:middle;margin-top:9px;" /></a>

				</div>

				<!--==| END: Bucket |==-->
				
				<!--==| START: Sorting |==-->
				<ul class="project_filters quality_sort" id="quality_sort" style="padding-left:8px; width:952px;">
					<li class="id"><a href="#" class="down" id="idsort" onClick="sortQuality(\'id\'); return false;">Defect ID</a></li>
					<li class="title"><a href="#" id="titlesort" onClick="sortQuality(\'title\'); return false;">title</a></li>
					<li class="severity"><a id="severitysort" href="#" onClick="sortQuality(\'severity\'); return false;">severity</a></li>
					<li class="status"><a id="statussort" href="#" onClick="sortQuality(\'status\'); return false;">status</a></li>
					<li class="category"><a id="categorysort" href="#" onClick="sortQuality(\'category\'); return false;">category</a></li>
					<li class="version"><a id="versionsort" href="#" onClick="sortQuality(\'version\'); return false;">version</a></li>
					<li class="opendate"><a id="open_datesort" href="#" onClick="sortQuality(\'open_date\'); return false;">open date</a></li>
					<li class="assigned"><a id="assigned_tosort" href="#" onClick="sortQuality(\'assigned_to\'); return false;">assigned to</a></li>
					<li class="detected_by"><a id="detected_bysort" href="#" onClick="sortQuality(\'detected_by\'); return false;">detected by</a></li>
					<li class="last_action"><a id="last_actionsort" href="#" onClick="sortQuality(\'last_action\'); return false;">Last Action</a></li>
				</ul>

				<!--==| END: Sorting |==-->

				<!--==| START: Work Orders |==-->
				<input type="hidden" name="active_wo" id="active_wo" value="" />
				<div id="qa_containter" class="quality_container">';
					
					echo '<!-- Company Break -->
				</div>
				<!--==| END: Work Orders |==-->
			
			<div style="display: none;" id="wo_dimmer_ajax" class="wo_save_box">
				<img alt="ajax-loader" src="/_images/ajax-loader.gif"/>
			</div>

			';
	} 
		
		else{
		print "<br/><br/><div style='font-size: 14px; color: #000000;margin-left: 15px;font-family: Verdana;'><strong>Please try the following</strong></div><br/><br/><div style='font-size: 13px; color: #000000;margin-left: 20px;font-family: Verdana;'>";
		
		print "<ul><li> Check your Spelling</li>";
		print "<li>Try more general words</li>";
		print "<li>Try using acronyms or using different words</li>";
		print "<li>Try using fewer words your search might be too specific</li></ul></div>";}
	

?>
