<? $this->headScript()
        ->setAllowArbitraryAttributes(true)
        ->appendFile( '/js/jquery.js','text/javascript')
        ->appendFile( '/js/jeditable.js','text/javascript')
        ->appendFile( '/js/jquery.ui.js','text/javascript')        
        ->appendFile( '/js/jquery.clockpick.js','text/javascript')                
        ->captureStart() ?>
        

 $(document).ready(function() {	
 
 
 	$(".edit_status").editable("/workorders/ajax/status",{ 
		data		: '<?=  json_encode($this->status); ?>',
		indicator	: 'Saving...',
		type		: 'select',
		submit		: 'OK',
		submitdata	: function(){ 
							var tmp = {};
							tmp["code"] = $(this).attr("name");
							tmp["name"] = $(".edit_status form select option:selected").text();							
							return tmp;		
						},
		cancel		: 'Cancel'
    	});


	$(".edit_resource").editable("/workorders/ajax/assign",{ 
		data		: '<?=  json_encode($this->resources); ?>',
		indicator	: 'Saving...',
		type		: 'select',
		submit		: 'OK',
		submitdata	: function(){ 
							var tmp = {};
							tmp["code"] = $(this).attr("name");
							tmp["name"] = $(".edit_resource form select option:selected").text();
							return tmp;		
						},
		cancel		: 'Cancel'
    	});
   
    $("#filter").click(function(e){     
    	top.location = "/workorders/index/list/filter/" + $("#filter").val();
	});
	
	$(".action").click(function(e){  
	    e.preventDefault();
	    
	    tmp = $(this).html();
	    if(tmp == "Archive") 
	    { 
	    
	    	$(this).html("Restore"); 
    	    $("#tr"+e.target.id).addClass("removed");    	     
	    
	    }
	    
	    if(tmp == "Restore") {
	    
	    		$(this).html("Archive"); 
    	        $("#tr"+e.target.id).removeClass("removed");    	     
	    
	    }

    	jQuery.get("/workorders/index/archive/id/" + e.target.id);	
    	
	});

 });
 <? $this->headScript()->captureEnd() ?>


<h3>Work Orders</h3>
<div class = "container">
	<div class = "span-20">
		<a href="<?php echo "$this->baseUrl/workorders/index/create" ?>" >Create a Workorder</a>
	</div>
	<div class = "span-4 last">	
		 Filters: 
		<select name="filter" id = "filter">
			<option <?= ($this->filter == "Show All") ? "selected" : '' ?>>Show All</option>
			<option <?= ($this->filter == "New") ? "selected" : '' ?>>New</option>
			<option <?= ($this->filter == "Open") ? "selected" : '' ?>>Open</option>
			<option <?= ($this->filter == "Closed") ? "selected" : '' ?>>Closed</option>			
			<option <?= ($this->filter == "Assigned to Me") ? "selected" : '' ?>>Assigned to Me</option>	
			<option <?= ($this->filter == "Requested by Me") ? "selected" : '' ?>>Requested by Me</option>	
			<option <?= ($this->filter == "Archived") ? "selected" : '' ?>>Archived</option>
			<option <?= ($this->filter == "Oldies") ? "selected" : '' ?>>Oldies</option>				
		</select>
	</div>
</div>

<div id="workorders">
<table>
	<tr>
		<td>
			Title
		</td>
		<td>
			Type
		</td>
		<td>
			Priority
		</td>
		<td>
			Status
		</td>
		<td>
			Requested By
		</td>
		<td>
			Assigned To
		</td>
		<td>
			Start Date
		</td>		
		<td>
			Estimated Close
		</td>
		<td>
			Action
		</td>

	</tr>
<?php
	if(isset($this->companies)) {
	foreach($this->companies as $key => $company)
	{
	if(isset($this->projects[$key])) {
?>
	<tr>
		<td colspan="9" bgcolor="#9BACB6" >
			<?php print $company['name']; ?>
		</td>
	<tr>
			
<?php 
		foreach($this->projects[$key] as $row) 
		{
?>
	<tr class="even">
		<td colspan=8>
			<?php print $row['id'].'-'.$row["project"]; ?>
		</td>			
		<td>
			<?php print $row["status"]; ?>
		</td>			
	</tr>
<?php 
			foreach($row['workorders'] as $detail)
			{
?>
			<tr bgcolor="<?= $detail->status == 'New' ? '#FFFF66': '#F5F5F5' ?>" name="row" id="tr<?= $detail->id ?>">
				<td>
					 <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'edit', 'id'=>$detail->id));?>"><?php print stripslashes($detail->title); ?></a>
				</td>
				<td>
					<?php print $detail->type; ?>
				</td>
				<td>
					<?php print $detail->priority; ?>
				</td>
				<td>
					<dt <?= !$this->isClient ? 'class="edit_status"': '' ?>  name="<?= $detail->id ?>" id="stat<?= $detail->id ?>"><?php print $detail->status; ?></dt>

				</td>
				<td>
					<?php print $detail->requester; ?>
				</td>
				<td>
					<dt <?= !$this->isClient ? 'class="edit_resource"': '' ?> name="<?= $detail->id ?>" id="rsrc<?= $detail->id ?>"><?php print $detail->resource; ?></dt>
				</td>
				<td>
					<?php print $detail->start_date; ?>
				</td>
				<td>
					<?php print $detail->est_due_date; ?>
				</td>
				<td>
				<?php 
					if(!$this->isClient) 
					{ 
				?>
					 <a href="<?php echo $this->url(array('controller'=>'index', 
            'action'=>'archive', 'id'=>$detail->id));?>" class="action" id="<?= $detail->id ?>"><?= $detail->archived ? "Restore" : "Archive" ?></a>
				<?php 
					}
				?>
				</td>
			</tr>
<?php
			}
	
		}	
	}
}
}else{
?>
	<tr class="even">
		<td colspan=8>
			You have no workorders...
		</td>			
	</tr>
<?php
}
?>
</table>
</div>


