<script type="text/javascript"><!--

$(document).ready(function(){

var cdate = new Date();
$('#startMonth').val(cdate.getMonth()+1);
$('#startDay').val(cdate.getDate());
$('#startYear').val(cdate.getFullYear());
//var 

    //showHideTime();
    $(".date_picker").datepicker({ 
		showOn: "both",
		buttonImage: "/_images/date_picker_trigger.gif", 
		buttonImageOnly: true ,
		duration: 'slow',
		minDate: 0+7
		//disable: true, 
		/*onClose:extractDate*/
	});

 if($('#checkDisable').val() != ''){
	 $(".date_picker").datepicker("disable");
 }  
   
$('#ev_requested_by').change(function(){
	var user_id = this.value;
	$.get("/events/index/userrequester/user_id/"+user_id,
	function(data){
		$('#requestor_info').html(data);
	});

});



});
function addCcUser(){
	var event_val = $('#event_id').val();
	var cc_user1 = $('#cc_user').val();
	var cc_list  = $('#cclist').val();
	var cc_user;
	if(cc_list !=''){
		cc_user = cc_list+','+cc_user1;
	}else{
		cc_user = cc_user1;
	}
	$('#cclist').val(cc_user.replace(',,',','));
	var cclist = $('#cclist').val();
	$.ajax({
		type: "GET",
		url: "/events/index/addccuser/eId/"+event_val+"/cc/"+cclist+"/addcc/"+cc_user1,
		success: function(msg) {
			//alert(msg);
			$('#cc_list').html(msg);
		}
	});

}

function removeCcUser(userId) {
	var event_val = $('#event_id').val();
	var cclist  = $('#cclist').val();
	if(cclist!=null)
	{
		var col_array= cclist.split(',');
		var part_num=0;
		var finalccList = "";

		while (part_num < col_array.length)
		{

			if(col_array[part_num]!=userId && col_array[part_num] !='')
			{
			  finalccList = finalccList + col_array[part_num] +',';
				//finalccList = finalccList + col_array[part_num];
			}

		    part_num+=1;
		}
	}
	//alert("dd"+finalccList);
	$('#cclist').val(finalccList);
	var cclist  = $('#cclist').val();
	//alert('add cc: '+woId+":"+cc);
	$.ajax({
		type: "GET",
		//url: "/_ajaxphp/wo_save_cc.php",
		//data: "woId="+woId+"&cc="+cclist+"&remove="+userId,
		url: "/events/index/addccuser/eId/"+event_val+"/cc/"+cclist+"/remove/"+userId,
		success: function(msg) {
			//alert(msg);
			$('#cc_list').html(msg);
		}
	});

	return false;
}
function deleteEvent(){
	$('#save_buttons_dimmer').css('display','block');
	$('.box_are_you_sure').css('display','block');
	
}

function deleteFinalEvent(){
	//$('#save_buttons_dimmer').css('display','block');
	//$('.box_are_you_sure').css('display','block');
	var event_val = $('#event_id').val();
	var ev_eventStatus = $('#ev_eventStatus').val();
	var cclist = $('#cclist').val();
	//var brandContainer = showSelectedValues();	
    var ev_assigned_to = $('#ev_assigned_to').val();
   // var prevStatus = $('#prevStatus').val();
	$.ajax({
		type: "GET",
		//url: "/_ajaxphp/wo_save_cc.php",
		//data: "woId="+woId+"&cc="+cclist+"&remove="+userId,
		url: "/events/index/deleteevent/eId/"+event_val+"/ev_eventStatus/"+ev_eventStatus+"/ev_assigned_to/"+ev_assigned_to,
		success: function(msg) {
			//alert(msg);
			$('#save_buttons_dimmer').css('display','none');
			$('.box_are_you_sure').css('display','none');
			window.location.href="/events/index/calendarview";
		}
	});
}
function saveEvent(){
	var flag = true;
	var ev_requested_by = $('#ev_requested_by').val();
	
	if(ev_requested_by == ''){
		$('#lb_ev_requested_by').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_requested_by').removeClass('alert_text');
	}
	var ev_brand_name = $('#ev_brand_name').val();
	if(ev_brand_name == ''){
		$('#lb_ev_brand_name').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_brand_name').removeClass('alert_text');
	}
	
	var ev_title = $('#ev_title').val();
	if(ev_title == ''){
		$('#lb_ev_title').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_title').removeClass('alert_text');
	}

	//time duration
	var ev_start_date = $('#ev_start_date').val();
	/*if(ev_start_date == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var ev_start_hr = $('#ev_start_hr').val();
	/*if(ev_start_date == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var ev_start_min = $('#ev_start_min').val();
	/*if(ev_start_min == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var ev_ampm = $('#ev_ampm').val();
	/*if(ev_ampm == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var start_time_zone = $('#ev_start_time_zone').val();
	/*if(start_time_zone == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var ev_end_date = $('#ev_end_date').val();
	/*if(ev_end_date == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/

	var ev_end_hr = $('#ev_end_hr').val();
	/*if(ev_end_hr == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var ev_end_min = $('#ev_end_min').val();
	
	/*if(ev_end_min == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	
	var ev_end_ampm = $('#ev_end_ampm').val();
	/*if(ev_end_ampm == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	var end_time_zone = $('#end_time_zone').val();
	/*if(ev_end_ampm == ''){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
	}else{
		
		$('#lb_ev_dur').removeClass('alert_text');
	}*/
	if((ev_start_date == '') || (ev_start_hr == '') || (ev_start_min == '') ||(ev_ampm == '')||(start_time_zone == '')
		||(ev_end_date == '') || (ev_end_hr == '') || (ev_end_min == '') ||(ev_end_ampm == '')){
		$('#lb_ev_dur').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		$('#lb_ev_dur').removeClass('alert_text');
	}
	//ENd time duration
	var ev_url = $('#ev_url').val();
	if((ev_url == '') || (ev_url=='http://')){
		$('#lb_ev_url').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_url').removeClass('alert_text');
	}
	var ev_traffic = $('#ev_traffic').val();
	if(ev_traffic == ''){
		$('#lb_ev_traffic').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_traffic').removeClass('alert_text');
	}
	var ev_loadTest = $('#ev_loadTest').val();
	if(ev_loadTest == ''){
		$('#lb_ev_loadTest').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_loadTest').removeClass('alert_text');
	}
	var ev_desc = $('#ev_desc').val();
	/*if(ev_desc == ''){
		$('#lb_ev_desc').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		
		$('#lb_ev_desc').removeClass('alert_text');
	}*/
	var ev_assigned_to = $('#ev_assigned_to').val();

	if(ev_assigned_to == ''){
		$('#lb_ev_assigned_to').addClass('alert_text');
		alertBox();
		flag =false;
	}else{
		$('#lb_ev_assigned_to').removeClass('alert_text');
	}
	var appFlag  = $('#app').val();
	var ev_eventStatus = $('#ev_eventStatus').val();
	 var prevStatus = $('#prevStatus').val();
	//4 is id of Approved status
	if(prevStatus  != 4 && ev_eventStatus == 4 && appFlag == 'notallow'){
		$('#save_buttons_dimmer').css('display','block');
		 $('.box_client_approval').css('display','inline');
		flag =false;
	}

	
	
			
	
	if(flag == true){
		var event_id = $('#event_id').val();
		var ev_eventStatus = $('#ev_eventStatus').val();
		var cclist = $('#cclist').val();
		var brandContainer = showSelectedValues();	
	    var prevAssigned = $('#prevAssigned').val();
	    var prevStatus = $('#prevStatus').val();
	    var pre_start_date = $('#pre_start_date').val();
	    var pre_end_date = $('#pre_end_date').val();
	    var pre_url = $('#pre_url').val();
	    var pre_traffic = $('#pre_traffic').val();
	    var prev_brand_name = $('#prev_brand_name').val();
	    
	    
		data = {ev_requested_by:ev_requested_by,ev_brand_name:ev_brand_name,ev_title:ev_title,ev_start_date:ev_start_date,ev_start_hr:ev_start_hr,ev_start_min:ev_start_min,ev_ampm:ev_ampm,start_time_zone:start_time_zone,ev_end_date:ev_end_date,ev_end_hr:ev_end_hr,ev_end_min:ev_end_min,ev_end_ampm:ev_end_ampm,ev_url:ev_url,ev_traffic:ev_traffic,ev_loadTest:ev_loadTest,ev_desc:ev_desc,ev_assigned_to:ev_assigned_to,end_time_zone:end_time_zone,cclist:cclist,ev_eventStatus:ev_eventStatus,event_id:event_id,brandContainer:brandContainer,prevAssigned:prevAssigned,prevStatus:prevStatus,pre_start_date:pre_start_date,pre_end_date:pre_end_date,pre_url:pre_url,pre_traffic:pre_traffic,prev_brand_name:prev_brand_name}
		$('#save_buttons_dimmer').css({display:'block'});
		$('#save_buttons_dimmer').css({backgroundColor:'#FFFFFF'});
		$('#save_buttons_dimmer').css({opacity:'0.7'});
		$('#save_buttons_dimmer').css({filter:'0.7'});
		$('#wo_dimmer_ajax').css({display:'block'});
		$.post("/events/index/checkdate",{ev_start_date:ev_start_date,ev_start_hr:ev_start_hr,ev_start_min:ev_start_min,ev_ampm:ev_ampm,ev_end_date:ev_end_date,ev_end_hr:ev_end_hr,ev_end_min:ev_end_min,ev_end_ampm:ev_end_ampm}, function(date_data) {
			  if(date_data == 'failed'){
				  $('.box_date_validation').css('display','inline');
				  flag = false;
			  }else{
				  $.ajax({
						type: "POST",
						url: "/events/index/addevent",
						data:data,
						success: function(msg) {
						$('#save_buttons_dimmer').css({display:'none'});
						$('#wo_dimmer_ajax').css({display:'none'});
						//create Event
						if(event_id == ''){
							window.location.href="/events/index/calendarview/?edate="+ev_start_date+"#event_date";
							}else{
							window.location.href="/events/index/create/?eId="+event_id;
							}
				  		}
					});	
			  }
			});

		
	}
}

function alertBox(){
	$('#save_buttons_dimmer').css('display','block');
	$('.box_please_fill').css('display','block');
	
}

function showSelectedValues()
{
  	return $("input[name=affected_brand]:checked").map(function (){
  	  	return this.value;
  	  	}).get().join(",");
}

function submitComment(){
	var comment = $('#comment').val();
	if($.trim(comment) == ''){
		$('.comment_validate').css('display','block');
		$('#cmt_box').addClass('alert_text');
		return false;
	}else{
		var event_id = $('#event_id').val();
		$('#save_buttons_dimmer').css({display:'block'});
		$('#save_buttons_dimmer').css({backgroundColor:'#FFFFFF'});
		$('#save_buttons_dimmer').css({opacity:'0.7'});
		$('#save_buttons_dimmer').css({filter:'0.7'});
		$('#wo_dimmer_ajax').css({display:'block'})
		var ev_eventStatus = $('#ev_eventStatus').val();
		var ev_assigned_to = $('#ev_assigned_to').val();
		data = {comment:comment,event_id:event_id,ev_eventStatus:ev_eventStatus,ev_assigned_to:ev_assigned_to}
		$.ajax({
			type: "POST",
			url: "/events/index/addcomment",
			data:data,
			success: function(msg) {
			$('#save_buttons_dimmer').css({display:'none'});
			$('#wo_dimmer_ajax').css({display:'none'});
			$('#comment_box').html(msg);
			}
		});
	return true;
	}
	
}


$(document).ready(function()
		{
		//var allVals = [];
	
			$("#all_brand").click(function()				
			{
				var checked_status = this.checked;
				$("input[@name=affected_brand]").each(function()
				{
					this.checked = checked_status;
					
				});
			});					
		});

//
--></script>
	<div class="events_content_container">		
        	<div class="main_actions_event" style="margin-left:-4px;padding: 3px 0pt 32px;">					
					<button onclick="window.location = '/events/index';"><span>Back To All Events</span></button>                    
			</div>
                		
			<div class="column_full_event">
				<!--==| START: Bucket |==-->

				<div class="title_med workorders_filter">
					<div class="title">New Event</div>
				</div>
				
				
				<div class="required_fields">
                	<span class="required_fields_text required_fields_asterisk">*</span> <span class="required_fields_text"><label>Required Fields</label></span>
                </div>
				<div class="content" style="margin-bottom: 7px;">
					<div class="wo_dimmer" id="wo_dimmer" style="display:none;"></div>
					<div class="wo_save_box" id="wo_dimmer_ajax" style="display: none;"><img src="/_images/ajax-loader.gif" alt="ajax-loader"/></div>
					
					<!--=========== COLUMN BREAK COLUMN 1===========-->
					<div class="event_content_col1">
						<ul>
                        	<li>                        	
								<label class="event_label" for='ev_requested_by' id="lb_ev_requested_by" >Requested By<span class="event_required_fields_asterisk">*</span></label>                        
                                <br>
								<br>
								<input  type="hidden" name="event_id"  id="event_id" value="<?php echo $this->escape($this->eventInfo['id']); ?>" >
								<input  type="hidden" name="app"  id="app" value="<?php echo $this->escape($this->app); ?>" >
                                <select id="ev_requested_by" name="ev_requested_by" class="field_medium"  <?php echo $this->disabled?>>
                              		<?php  echo EventDisplay::getUserOptionHTML($this->eventInfo['requested_by']); ?>
                                </select>                                     
                            </li>      
							<li class="li_brand">                        	
								<label class="event_label" id="lb_ev_brand_name">Brand<span class="event_required_fields_asterisk">*</span></label>                        
                                <br>
								<br>
								 <input type='hidden' id="prev_brand_name" name="prev_brand_name" value="<?php echo $this->eventInfo['company_id']?>">
                                <select id="ev_brand_name" name="ev_brand_name" class="field_medium" <?php echo $this->disabled?>>
                                	<option value="">--Select Brand--</option>
                               		<?php echo EventDisplay::getCompanyHTML($this->eventInfo['company_id']); ?>
                                </select>                                     
                            </li>
							<li class="li_title">                        	
								<label class="event_label" id="lb_ev_title" >Event Title<span class="event_required_fields_asterisk">*</span></label>                        
                                <br>
								<br>
								<input type="text" value="<?php echo $this->escape($this->eventInfo['title'])?>" class="input_field" id="ev_title" name="ev_title" maxlength='70' <?php echo $this->disabled?> >            
                            </li>                                                                                    
                            <li>
                                <label class="event_label" id="lb_ev_dur" >Event Duration<span class="event_required_fields_asterisk">*</span></label>
                                <br>
								<br>
                                <span class="event_copy event_copy_margin">
                                    If your event is sooner than one week from today, contact Ops<br> 
                                    directly at dps-support@nbcuni.com - do not use this form. 
                                </span>
                            </li>
                        	<li style="margin-left:-10px;margin-top:-1px;">
                        	<?php 
                        	$eStartDate ='';
                        	$eStartHr = '';
                        	$eStartMin = '';
                        	$eStartAmpm = '';
                        	$eEndDate = '';
                        	$eStartHr = '';
                        	$eStartMin ='';
                        	$eStartAmpm ='';
                        	$timeZone = '';
                        	
                        	if(!empty($this->eventInfo['id'])){
                        		//echo $this->eventInfo['start_date'];
                        		//$eStartDateTime = date("m/d/Y h:i A",strtotime($this->eventInfo['start_date']));
                        		$eStartDate = date("m/d/Y",strtotime($this->eventInfo['start_date']));
                        		$eStartHr = date("h",strtotime($this->eventInfo['start_date']));
                        		$eStartMin = date("i",strtotime($this->eventInfo['start_date']));
                        		$eStartAmpm = date("A",strtotime($this->eventInfo['start_date']));
                        		
                        		$eEndDate = date("m/d/Y",strtotime($this->eventInfo['completed_date']));
                        		$eEndHr = date("h",strtotime($this->eventInfo['completed_date']));
                        		$eEndMin = date("i",strtotime($this->eventInfo['completed_date']));
                        		$eEndAmpm = date("A",strtotime($this->eventInfo['completed_date']));
                        		$timeZone  = $this->eventInfo['time_zone'];
                        	} 
                        	 ?>
                        	 <input type="hidden" name="checkDisable" id="checkDisable" value="<?php  echo $this->disabled ?>">
                        		<input type="text" readonly="readonly" class="date_picker" name="ev_start_date" id="ev_start_date" value="<?php echo $eStartDate ?>" <?php echo $this->disabled?>>  
                             	<input type="hidden" name="pre_start_date" id="pre_start_date" value="<?php echo strtotime($this->eventInfo['start_date']) ?>">
                             	<input type="hidden" name="pre_end_date" id="pre_end_date" value="<?php echo strtotime($this->eventInfo['completed_date']) ?>">
                             </li>
                            <li style="margin-left:-10px;">
	                            <select  name="ev_start_hr" id="ev_start_hr" class="small" <?php echo $this->disabled?>>
									<?php echo EventDisplay::getDailyHours($eStartHr); ?>
								</select>
								
								<select  name="ev_start_min" id="ev_start_min" class="small"  <?php echo $this->disabled?>>
									<?php echo EventDisplay::getDailyMin($eStartMin); ?>
								</select>
								
								<label for="ev_ampm" class="inside_label_small" style="display:none;">AM/PM:</label>
								<select name="ev_ampm" id="ev_ampm" class="input_field_month"  <?php echo $this->disabled?> style="margin-left:12px;">
									<?php echo EventDisplay::getAmPm($eStartAmpm) ?>
								</select>	
								
								<select class="input_field_timezone" id="ev_start_time_zone" name="ev_start_time_zone" style="width:165px;margin-left:2px;" <?php echo $this->disabled?>>
	                               	<?php echo EventDisplay::getTimeZone($timeZone);?>                                    
	                            </select>                                                                 
                            </li>
                            <li style="margin-left:-10px;">
                            	<span class="event_copy event_copy_to">to -</span>                            
							</li>  
						  	<li class="li_dates" style="margin-left:-10px;margin-top:-1px;">
                        		<input type="text" class="date_picker" name="ev_end_date" readonly=readonly" <?php echo $this->disabled?> id="ev_end_date" value="<?php echo $eEndDate?>">  
                            </li>
                            <li style="margin-left:-10px;margin-top:8px;">
							<select  name="ev_end_hr" id="ev_end_hr" class="small" <?php echo $this->disabled?> >
								<?php echo EventDisplay::getDailyHours($eEndHr); ?>
							</select>
							
							<select  name="ev_end_min" id="ev_end_min" class="small" <?php echo $this->disabled?>>
								<?php echo EventDisplay::getDailyMin($eEndMin); ?>
							</select>
							<label for="ev_end_ampm" class="inside_label_small" style="display:none;">AM/PM:</label>
								<select name="ev_end_ampm" id="ev_end_ampm" class="input_field_month"  <?php echo $this->disabled?> style="margin-left:12px;">
									<?php echo EventDisplay::getAmPm($eEndAmpm) ?>
								</select>	
								<div style="display:none;">
								<select class="input_field_timezone" id="end_time_zone" name="end_time_zone" style="width:110px" <?php echo $this->disabled?>>
                               	<?php echo EventDisplay::getTimeZone($timeZone);?>                                    
                                </select>  
                                </div>                                                                
                            </li>  
                            <li >
                                <label class="event_label" id="lb_ev_url">URL<span class="event_required_fields_asterisk">*</span></label>
                                <br>
								<br>
								<?php $url = (empty($this->eventInfo['example_url']))?'http://':$this->eventInfo['example_url'] ?>
								<input type="hidden" value="<?php echo $url ?>" class="input_field" id="pre_url" name="pre_url">								
								<input type="text" value="<?php echo $url ?>" class="input_field" id="ev_url" name="ev_url" <?php echo $this->disabled?>>
							</li> 
                            <li>
                                <label class="event_label" id="lb_ev_traffic" >Anticipated Traffic<span class="event_required_fields_asterisk">*</span></label>
                                <br>
								<br>
								<input type="hidden" value="<?php echo $this->eventInfo['anticipated_traffic'] ?>" class="input_field" name="pre_traffic" id="pre_traffic">
                               
                                <select class="field_medium" name="ev_traffic" id="ev_traffic" <?php echo $this->disabled ?> >
                                	<option value=''>Select Approximate Range</option>
                                	<?php echo EventDisplay::getAnticipated($this->eventInfo['anticipated_traffic']); ?>
                                </select>&nbsp; <span style="margin-bottom:-5px">per hour</span>
							</li> 
							<li>
                                <label class="event_label" id="lb_ev_loadTest" >Load Test Completed?<span class="event_required_fields_asterisk">*</span></label>
                                <br>
								<br>
								
                                <select class="field_medium" name="ev_loadTest" id="ev_loadTest" <?php echo $this->disabled?>>
                                	<option value=''>Select</option>
                                <?php echo EventDisplay::getLoadTestig($this->eventInfo['load_test_status'])?>                                    
                                </select>
							</li> 
							<li>
                                <label class="event_label" id="lb_ev_desc">Event Description</label>
                                <br>
								<br>
                                <textarea class="field_large text_in_fields textarea_margin" id="ev_desc" name="ev_desc" <?php echo $this->disabled?>><?php echo htmlentities($this->eventInfo['body'],ENT_NOQUOTES,'UTF-8')?></textarea>
							</li> 							                                                                             
                        </ul>
					</div>
					
					<!-- =========== COLUMN BREAK COLUMN 2===========-->
					<div class="workorder_content_col2">
						<div class="side_bucket_container" id="requestor_info">
						<?php 
						$uid = (empty($this->eventInfo['requested_by']))?$this->User_id:$this->eventInfo['requested_by'];
						$userInfo = EventDisplay::getRequestorInfo($uid); ?>
						<?php //p($userInfo);?>
							<div class="side_bucket_title">Requestor's Information</div>
							<div class="side_bucket_content">
								<img src="<?php echo $userInfo[0]['user_img'] ?>" id="requestor_photo" class="requestor_photo">
								<ul class="requestor_fields">
									<li>
										<label for="requestor_name">Requested By:</label>
										<input class="field_small readonly" name="requestor_name" id="requestor_name" type="text" value="<?php echo $userInfo[0]['full_name'] ?>" readonly />
									</li>
									<li>
										<label for="requestor_email">E-mail:</label>
										<input class="field_small readonly" name="requestor_email" id="requestor_email" type="text" value="<?php echo $userInfo[0]['email'] ?>" readonly />
									</li>
									<li>
										<label for="requestor_phone">Phone:</label>
										<input class="field_small readonly" name="requestor_phone" id="requestor_phone" type="text" value="<?php echo $userInfo[0]['phone_office'] ?>" readonly />
									</li>
								</ul>
								<div class="clearer"></div>
							</div>
						</div>
						
						<div class="side_bucket_container bucket_container_last">
							<div class="side_bucket_title">Event Management</div>
							<div class="side_bucket_content">
							<?php  $assignedData = (empty($this->eventInfo['creation_date']))?date("Y-m-d"): $this->eventInfo['creation_date']?>
								<input type="hidden" name="ev_assigned_date" id="ev_assigned_date" value="<?php echo $assignedData ?>" />
								<ul class="project_management">
									<li>
										<input type="hidden" name="prevStatus" id="prevStatus" value="<?php echo $this->eventInfo['status'] ?>" />
										<label for="wo_status" id="lb_ev_eventStatus">Status:</label>
										
										<select  class="field_small" name="ev_eventStatus" id="ev_eventStatus" <?php echo $this->disabled?>>
											 <?php echo EventDisplay::getEventStatus($this->eventInfo['status'])?>
										</select>
									</li>
									<li >
									 
									
										<label for="ev_assigned_to" id="lb_ev_assigned_to">Assigned to:</label>
										<input type="hidden" name="prevAssigned" id="prevAssigned" value="<?php echo $this->eventInfo['assigned_to'] ?>" />
										<select class="field_small" name="ev_assigned_to" id="ev_assigned_to"  <?php echo $this->disabled?>>
											<?php if(empty($this->opsPerson)){
											  echo EventDisplay::getUserAssignOptionEditHTML($this->eventInfo['assigned_to']);
												} else{
											  echo EventDisplay::getUserAssignOptionOpersionEditHTML($this->eventInfo['assigned_to'],false,$this->opsPerson);	
											  }?>
										</select>
									</li>
									<?php  $assignedData = (empty($this->eventInfo['creation_date']))?date("m/d/Y h:i A"): date("m/d/Y h:i A",strtotime($this->eventInfo['creation_date']))?>
									<li>
										<label for="ev_pm_start_date">Opened Date:</label>
											<input name="ev_pm_start_date" id="ev_pm_start_date" readonly="readonly" class="readonly" type="text" value="<?php echo $assignedData ?>" <?php echo $this->disabled?>>
									</li>
									<li>
									<?php
									$displayMDate = '';
									if(!empty($this->eventInfo['id'])){
										$mDate = EventDisplay::getEventAuditInfo($this->eventInfo['id'],'log_date');
										$displayMDate = (empty($this->eventInfo['id']))?'':date("m/d/Y h:i A",strtotime($mDate));
									}
									 
									 
									?>
										<label for="ev_modified_date">Last Modified:</label>
										<input name="ev_modified_date" id="ev_modified_date" value="<?php echo $displayMDate ?>" readonly="readonly" class="readonly" type="text"  <?php echo $this->disabled?>>
									</li>
								</ul>
								<div class="clearer"></div>
							</div>
						</div>
						<div class="workorder_content_col4">
						<div class="side_bucket_container bucket_container_last">
							<div class="side_bucket_title">CC List</div>
							<div class="side_bucket_content cc_box">
								<input type='hidden' name='cclist' id='cclist' value="<?php echo $this->cclist?>"> 
								<ul id="cc_list">
								<?php //echo $eId = $_GET['eId'];  ?>
									<?php if(ISSET($_GET['eId'])) :?>
										<?php if(count($this->cc_user_row) > 0) : ?>
										<?php foreach($this->cc_user_row as $userKey => $userInfo) : ?>
											<li>
											<div class='cclist_name'><?php echo ucfirst($userInfo[0]['full_name']) ?></div>
											<button class="status cclist_remover" onClick="removeCcUser(<?php echo $userInfo[0]['id']?>); return false;"><span>remove</span></button>
											</li>
										<?php endforeach; ?>
									<?php endif ?>
								<?php endif ?>	
								</ul>
								
								<div style="display:<?php echo $this->ev_buttons; ?>;" id="select_cc" class="cclist_actions" >
									<select class="cc_field" id="cc_user" name="cc_user" >
										<?php echo EventDisplay::getUserOptionEditHTML(); ?>
									</select>
									<button onclick="addCcUser(); $('#select_cc').css({display:'none'});$('#add_cc').css({display:'block'}); return false;" style="clear:left; margin-left:7px;" class="secondary">
										<span>Add</span>
									</button>
									<button onclick="$('#add_cc').css({display:'block'}); $('#select_cc').css({display:'none'}); return false;" class="cancel" >
										<span>Cancel</span>
									</button>
								</div>
								
								<div id="add_cc" class="cclist_actions" style="display:<?php echo $this->ev_buttons; ?>;">
									<button onclick="$('#add_cc').css({display:'none'});$('#select_cc').css({display:'block'}); return false;" class="secondary" style="margin:0 10px 10px 10px;">
										<span>+ Add Person to CC List</span>
									</button>
								</div>
								<div class="clearer"></div>
							</div>
						</div>
					</div>
					</div>
					<div class="clearer"></div>
					<div class='ev_dimmer' style="display:none"></div>
					<!--=========== COLUMN BREAK COLUMN 3===========-->
					<div class="workorder_content_col3_brands " style="height:auto;display:<?php echo $this->affectedBrandDisplay ?>;">                       	
						<label class="event_label">Brands Affected (Ops Use Only):</label> 
						<br>
						<br>
						<div style="margin-left:-11px;margin-bottom:10px;">
						<input type="checkbox" name="all_brand" id="all_brand"  <?php echo $this->affectedBrand?> /><span class="event_brand_text">&nbsp;&nbsp;&nbsp;All Brands</span>
						</div>
						<br/>
						<div class="clearer"></div>
						<div class="event_brand">
							
							<?php
							$count = 1;
							$rsCompanyHtml = array(); 
							$affectedBrandarray = array();
							$checked = '';
							$rsCompanyHtml = EventDisplay::getCompanyListHTML(); ?>
							<ul>
								<?php if(count($rsCompanyHtml) > 0):?>
								<?php 
									$affectedBrandStr = $this->eventInfo['affected_company_list']; 
									if(!empty($affectedBrandStr)){
										$affectedBrandarray = explode(",",$affectedBrandStr);
											
									}
									
								
								?>
								<?php foreach($rsCompanyHtml as $comkey => $compVal):?>
								<?php 
									if(in_array($compVal['id'],$affectedBrandarray)){
										$checked = " checked='checked'";
									}else{
										$checked ='';
									}
								
								?>
								<li>
									<input type="checkbox" id="affected_brand"  name="affected_brand" value="<?php echo $compVal['id'] ?>" <?php echo $checked ?>  <?php echo $this->affectedBrand?>> <span class="event_brand_text"><?php echo $compVal['name'] ?></span>
								</li>
								<?php 
								if($count%5 == 0):?>
							</ul>
						</div>                       
						<div class="event_brand">
							<ul>
															
							<?php endif; 
							$count++;
								
							?>
							<?php endforeach; ?>
						<?php endif; ?>
					<!--=========== COLUMN BREAK ===========-->
				</div>

				<div class="clearer"></div>			
				
				<!--==| END: Bucket |==-->
				<div class="message_cancel message_close message_required message_workorder_audit message_reopen request_type_msg severity1_msg severity2_msg severity3_msg request_type_msg message_outage_submit" style="width:3000px;height:1024px;position:fixed;background-color:#fffff;z-index:1.0;margin-top:-500px;margin-left:-630px;opacity: 0.3;filter:alpha(opacity=30);zoom:1.0;"></div>
				<div class="message_required">
					<p>
						Please fill in the required fields?
					</p>					
					<div style="clear: both;"></div>
					
					<div class="duplicate_buttons">
						<button onClick="$('.message_required').css({display:'none'}); return false;"><span>OK</span></button>
						<div style="clear: both;"></div>
					</div>
				</div>
			</div>			
			<div class="clearer"></div>
		</div>			
				
        <!--Please fill in all required fields Box-->
		<div class="message_box box_please_fill" style="display:none;">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                            	Please fill in all <span class="alert_text">required</span> fields.
                            </div>
                            <button onClick="$('.message_box').css({display:'none'});$('#save_buttons_dimmer').css('display','none'); return false;"><span>Ok</span></button>                    
                        </li>
                    </ul>
		</div>
        <!--Please fill in all required fields Box END -->        
        
        <!--Sorry, events taking place earlier than one week from today Box-->
		<div class="message_box box_sorry">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                            	Sorry, events taking place earlier than one<br>
                                week from today cannot be submitted with<br>
                                this form. Please contact Ops directly at:
                                <span class="blue_text">dps-support@nbcuni.com</span>
                            </div>
                            <button><span>Ok</span></button>                    
                        </li>
                    </ul>
		</div>
        <!--Sorry, events taking place earlier than one week from today Box END -->
         <!--Start date time must be greater than End time-->
		<div class="message_box box_date_validation">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                            	Event end date time must be greater<br/> than event start date time
                            </div>
                            <button onClick="$('.box_date_validation').css({display:'none'});$('#save_buttons_dimmer').css({display:'none'});$('#wo_dimmer_ajax').css({display:'none'}); return false;"><span>Ok</span></button>                    
                        </li>
                    </ul>
		</div>
        <!--Start date time must be greater than End time End -->
        <!-- Client type user can't approve the events -->
        <div class="message_box box_client_approval">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                            	You can't approve the event.<br/>
                            	Please contact Ops directly at:
                                <span class="blue_text">dps-support@nbcuni.com</span>
                            </div>
                            <button onClick="$('.box_client_approval').css({display:'none'});$('#save_buttons_dimmer').css({display:'none'});$('#wo_dimmer_ajax').css({display:'none'}); return false;"><span>Ok</span></button>                    
                        </li>
                    </ul>
		</div>
        
        <!--Are you sure you want to delete Box -->
		<div class="message_box box_are_you_sure">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                                Are you sure you want to delete<br>
                                this event? This cannot be undone.
                            </div>
                            <button onClick="$('.box_are_you_sure').css({display:'none'});$('#save_buttons_dimmer').css({display:'none'}); return false;"><span>Cancel</span></button>
							<button class="cancel" onClick='deleteFinalEvent();'><span>Delete Event</span></button>                                                
                        </li>
                    </ul>
		</div>
	
		 <!--required fields -->
		<div class="message_box comment_validate">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                                Please fill in all <span class="alert_text">required</span> fields
                            </div>
                            <button onClick="$('.comment_validate').css({display:'none'});return false;"><span>Ok</span></button>
							                                               
                        </li>
                    </ul>
		</div>
		<!--Cancel box -->
		<div class="message_box cancle_box">
					<ul class="event_list shadow_new_event">
                    	<li>
                        	<div class="message_box_text">
                              You are about to leave this event. <br/>Any unsaved information will be lost.<br />Do you want to continue?
                            </div>
                            <button onClick="document.location = '/events/'; return false;"><span>Yes</span></button> 
							<button class="cancel" onClick="$('.cancle_box').css({display:'none'});$('#save_buttons_dimmer').css({display:'none'});  return false;"><span>No</span></button>

							                                               
                        </li>
                    </ul>
		</div>
         
     <div class="wo_dimmer" id="save_buttons_dimmer" style="display:none;"></div>	
      <div style="display:<?php echo $this->ev_buttons ?>;margin-left:20px;">
       
    <?php if($this->escape($this->eventInfo['id'])): ?>
       <button id="wo_delete_save" onClick="deleteEvent(); return false;" class='cancel'><span>Delete Event</span></button>
      <?php endif ?>
      <div class="floatright" style="float:left">
	   <button onClick="$('.cancle_box').css({display:'block'}); $('#save_buttons_dimmer').css({display:'block'});return false;"><span>cancel</span></button>
	   <button id="wo_save" onClick="saveEvent(); return false;" ><span><?php echo $this->saveButton; ?></span></button>
	   </div>
	   
	</div>
	
 <?php if(!empty($this->eventInfo['id'])): ?>
	
		<div class="content" id="comment_box">
			<div style="margin:10px;height:10px;"></div>	
			<div class="workorder_content_col3" style="padding-left: 24px;" >
				<div class="main_bucket_container" >
					<div class="main_bucket_title" ><h4 id="number_of_comments">Comments (<?php echo (count($this->commentInfo) == 0)?0:count($this->commentInfo) ?>)</h4></div>
						<div class="main_bucket_content" >
							<ul class="comments" id="comments_list">
							<?php 
							//p($this->commentInfo);
							$pattern = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";
							if(count($this->commentInfo) > 0):
								foreach($this->commentInfo as $k => $commentVal):
									$comment = $commentVal['comment'];
									$text_string = preg_replace($pattern, "<a href=\"\\0\"?phpMyAdmin=uMSzDU7o3aUDmXyBqXX6JVQaIO3&phpMyAdmin=8d6c4cc61727t4d965138r21cd rel=\"nofollow\" target='_blank'>\\0</a>",htmlentities($comment,ENT_NOQUOTES, 'UTF-8'));
									$text_string = nl2br($text_string);
									$where = " id = ".$commentVal['user_id'];									
									$comment_user_data = EventDisplay::getTableData('users', '*',$where);
								?>
							<li>
								<img src="<?php echo $comment_user_data['user_img'] ?>" class="comment_photo" />
								<div class="comment_body">
									<p><strong><?php echo ucfirst($comment_user_data['first_name']) .' ' .ucfirst($comment_user_data['last_name']) ?></strong><br>
									<em><?php echo @date("D M j \t g:i a", strtotime($commentVal['date'])) ?></em></p>
								     <p><?php echo $text_string ?></p>                                                 
								</div>
							</li>
						<?php endforeach;?>
						<?php endif;?>	
						</ul>
					
					<ul class="comment_field_container">
						<li><label id="cmt_box" for="comment" class='event_label'  style="width:130px;text-align:left;"">Add a comment:</label></li>
						<li><textarea name="comment" id="comment" class="field_large" style="width:450px;"></textarea></li>
					</ul>
					<div class="new_comment_actions">
						<button class="secondary" onClick="return submitComment(); return false;">
							<span>Submit Comment</span>
						</button>
					</div>
					<div class="clearer"></div>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>
				
			
