<ul id="WeekRow">
	<li class="PreviousWeek"><a href="javascript:void(0);" onclick="app.previousWeek();">previous week</a></li>
<?php foreach ($this->items["weekdays"] as $day){ ?>
	<li><?= strftime("%A, %m/%d/%y", strtotime($day)) ?></li>
<?php } ?>
	<li class="NextWeek"><a href="javascript:void(0);" onclick="app.nextWeek();">next week</a></li>
</ul>

<ul id="ResourceGrid">

<?php foreach ($this->items["users"] as $user){ ?>
<?php
	$user_id = $user["id"];
	$first_name = "first-name";
	$last_name = "last-name";
	$active_user = !empty($this->items["resourceblocks"][$user_id]) ? $this->items["resourceblocks"][$user_id] : "";
?>
	<li> 
	<div class="UserName"><?=$user[$first_name]?> <?=$user[$last_name]?></div>
		<ul class="UserWeek uid<?=$user_id?>">
		<?php foreach ($this->items["weekdays"] as $day){ ?>
		<li>
			<ul class="UserDay d<?=$day?>">
			<?php foreach ($this->items["dayparts"] as $daypart){ ?>
				<?php
					$active_user_daypart = !empty($active_user[$day][$daypart]) ? $active_user[$day][$daypart] : "";
					$dpStatus = $active_user_daypart ? $active_user_daypart["Status"] : "";
					$project_id = $active_user_daypart ? $active_user[$day][$daypart]["ProjectID"] : "";
					$project_name = $project_id ? $this->items["projects"][$project_id]["name"] : "";
				?>
				<li onClick="app.clk(this);"
					class="<?php if ($dpStatus)print "Status$dpStatus";?> dp<?=$daypart?>"><span><?=$project_name?></span></li>
			<?php } ?>
			</ul>
		</li>
		<?php } ?>
		</ul>
	</li>
<?php } ?>
</ul>


<div id="ActionMenu">
<ul>
<li><a href="javascript:app.saveDayparts(INT)">Internal</a></li>
<li><a href="javascript:app.saveDayparts(OOO)">Out of the Office</a></li>
<li><a href="javascript:app.cancelSelected()">Clear Selection(s)</a></li>
</ul>
<div id="CompanyMenu" class="yuimenu">
	<div class="bd">
		<ul id="CompanyListUL" class="first-of-type"> 
		<?php
			foreach ($this->items["projects_by_company"] as $company => $projects){
			$counter = 1;
		?>
			<li class="CoList yuimenuitem">
				<a href="javascript:void(0);" class="yuimenuitemlabel"><span><?=$company?></span></a>
				<div class="yuimenu">
					<div class="bd">
						<ul class="ProjectList" id="co<?=$counter++?>">
						<?php foreach ($projects as $project) { ?>
							<li><a href="javascript:void(0);" onclick="app.saveDayparts(ACT,'<?=$project["id"]?>',this);"><span><?=$project["name"]?></span></a></li>
						<?php } ?>
						</ul>
					</div>
				</div>
			</li>
		<?php } ?>
		</ul>
	</div>
</div>
</div>
