<?PHP

	$wo_id = $this->wo_id;
	$vars = $this->vars;
	$status_html = $this->status;
	$assigned_html = $this->assigned;
	$comment_data = $this->comment;

	echo "<div><a href='/qaworkorders/index/list'>All Work Orders</a></div>";
	echo "
	<div>
		<form action='/qaworkorders/index/mobileedit?wo_id=" . $wo_id . "' name='save_wo' method='post'>
		<input type='hidden' name='save_type' value='save_wo'>
		<table width='600px'>
			<tr><td colspan='2'><strong>Work Order Information</strong></td></tr>
				<tr><td width='30%'>Project:</td><td width='60%'>" . $vars['project_name'] . "</td></tr>
				<tr><td width='30%'>Priority:</td><td width='60%'>" . $vars['priority'] . "</td></tr>
				<tr><td width='30%'>Title:</td><td width='60%'>" . $vars['title'] . "</td></tr>
				<tr><td width='30%'>Example URL:</td><td width='60%'>" . $vars['url'] . "</td></tr>
				<tr><td width='30%'>Work Order Description:</td><td width='60%'>" . $vars['description'] . "</td></tr>
			<tr><td colspan='2'><strong>Requestor Information</strong></td></tr>
				<tr><td width='30%'>Requested By:</td><td width='60%'>" . $vars['requested_user'] . "</td></tr>
				<tr><td width='30%'>E-mail:</td><td width='60%'>" . $vars['email'] . "</td></tr>
				<tr><td width='30%'>Phone:</td><td width='60%'>" . $vars['contact'] . "</td></tr>
			<tr><td colspan='2'><strong>Project Management</strong></td></tr>
				<tr><td width='30%'>Work Order Status:</td><td width='60%'>"
					."<select class='field_small' name='wo_status' id='wo_status'>"
						.$status_html
					."</select>"
				."</td></tr>
				<tr><td width='30%'>Assigned To:</td><td width='60%'>"
					."<select class='field_small' name='wo_assigned_user' id='wo_assigned_user'>"
						.$assigned_html
					."</select>"
				."</td></tr>
				<tr><td width='30%'>Start Date:</td><td width='60%'>" . $vars['start_date'] . "</td></tr>
				<tr><td width='30%'>Estimated Completion Date:</td><td width='60%'>" . $vars['completed_date'] . "</td></tr>
				<tr><td width='30%'>Close Date:</td><td width='60%'>" . $vars['closed_date'] . "</td></tr>
		</table>
		<table>
			<tr><td valign='top'><button onClick='save_wo.submit();'>SAVE</button></td>
		</form>
			<td><form name='close_wo' action='/qaworkorders/index/mobileedit?wo_id=" . $wo_id . "' method='post'>
				<input type='hidden' name='save_type' value='close_wo'>
				<button onClick='close_wo.submit();'>CLOSE</button></form></td>
			</tr>
		</table>
	</div>";

	echo "
	<div>
		<table width='600px'>
			<h4>Comments (" . sizeof($comment_data) . ")</h4>
			<tr>
				<td>";
								
		for($cx = 0; $cx < sizeof($comment_data); $cx++) {
			echo '<div>
					<p><strong>' . $comment_data[$cx]['name'] .'</strong><br>
					<em>' . $comment_data[$cx]['timestamp'] .'</em></p>
					<p>' . $comment_data[$cx]['comment_text'] .'</p>
				</div>';
		}

	echo		"</td>
			</tr>
			<tr>
				<form name='comment_wo' method='post' action='/qaworkorders/index/mobileedit?wo_id=" . $wo_id . "'>
					<input type='hidden' name='save_type' value='comment_wo'>
					<table width='500px'>
						<tr>
							<td width='25%' valign='top'>New Comment:</td>
							<td width='65%'><textarea name='comment' id='comment'  cols='40' rows='3'></textarea></td>
						</tr>
						<tr><td align='right' colspan='2'><button onClick='comment_wo.submit();'>SUBMIT</button></td></tr>
				</form>
			</tr>
		</table>
	</div>";

?>