
<div id="ActionMenu">
<ul>
<li class="Deselect"><a href="javascript:void(0);" onclick="javascript:app.cancelSelected()">De-select current selection</a></li>
<li class="Internal"><a href="javascript:void(0);" onclick="javascript:app.saveDayparts(app.INT)">Overhead / Internal</a></li>
<li class="OutOfOffice"><a href="javascript:void(0);" onclick="javascript:app.saveDayparts(app.OOO)">Out of Office</a></li>
<li class="Unassigned"><a href="javascript:void(0);" onclick="javascript:app.saveDayparts(app.UNA)">Unassigned</a></li>
</ul>
<ul id="BookingMenu">
	<li><b>Hours</b></li>
	<li><input id="BookingHours_book" type="radio" name="hoursStyle" value="booked" checked="checked" />
		<label for="BookingHours_book">actual</label></li>
	<li><input id="BookingHours_assign" type="radio" name="hoursStyle" value="assigned" />
		<label for="BookingHours_assign">scheduled</label></li>
</ul>
</div>
<div id="CompanyMenuContainer" class="yuimenu">
	<div id="CompanyMenu" class="yuimenu">
		<div class="bd">
			<ul id="CompanyListUL" class="first-of-type"> 
			<?php
				foreach ($this->items["projects_by_company"] as $company => $projects){
				$counter = 1;
			?>
				<li class="CoList yuimenuitem">
					<a href="javascript:void(0);" class="yuimenuitemlabel"><span><?=$company?></span></a>
					<div class="yuimenu">
						<div class="bd">
							<ul class="ProjectList" id="co<?=$counter++?>">
							<?php foreach ($projects as $project) { ?>
								<li><a href="javascript:void(0);" onclick="var hrs=$('BookingHours_book').checked ? app.ACT : app.ASN; app.saveDayparts(hrs,'<?=$project["id"]?>',this);"><span><?=$project["name"]?></span></a></li>
							<?php } ?>
							</ul>
						</div>
					</div>
				</li>
			<?php } ?>
			</ul>
		</div>
	</div>
</div>
