<?PHP
	/*
	Base Zend index file loaded for the index.php file
	*/
		$query = $_POST['search_text'];
		$search_par = $_POST['search_par'];
		if($search_par[0]=='All'){
                $string='';
                }
                elseif($search_par[0]=='Defect'){
                $string='%20AND%20categories:quality';
                }
                elseif($search_par[0]=='WorkO'){
                $string='%20AND%20categories:workorder';
                }
       		 $url = 'http://ec2-75-101-162-191.compute-1.amazonaws.com:8080/solr/lighthouse_active/select?q='.urlencode($query).$string.'&start=0&rows=2000';
                $ch = curl_init();
                $request='<request>'.$request.'</request>';
                curl_setopt($ch, CURLOPT_URL, $url);
                if(defined('HTTP_PROXY') && HTTP_PROXY!='')
                {
                        curl_setopt($ch,CURLOPT_PROXY,HTTP_PROXY);
                        curl_setopt($ch,CURLOPT_HTTPPROXYTUNNEL,true);
                        curl_setopt($ch,CURLOPT_PROXYTYPE,CURLPROXY_HTTP);
                }
                curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
                curl_setopt ($ch, CURLOPT_POST, 1);
                curl_setopt ($ch, CURLOPT_POSTFIELDS, $request);
                curl_setopt($ch, CURLOPT_HEADER, false);
                curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/xml', 'Content-Type: application/xml'));
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch,CURLOPT_USERPWD,BC_USER . ":" . BC_PASSWORD);
                if(preg_match('/^(http)/',$url)) curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
                $response = curl_exec($ch);
                curl_close($ch);

        $xml = (array)simplexml_load_string($response);
        $titleDesc = array();
        $desc = array();
        $count_qa=0;$count_wo=0;
        if(count($xml) > 0){
        foreach($xml as $key =>$val){
                if($key == 'result'){
                $result_found = $val[numFound];
                                $searchResult =  $val->doc;
                                if(count($searchResult) > 0){
                                foreach($searchResult as $k => $v){
                                        if(count($searchResult) > 0){
                                                foreach($searchResult as $sKey => $eVal){
                                                       /* $comments='';
                                                        for($i=0;$i<count($eVal->arr[1]->str);$i++)
                                                        {$no = $i+1;
                                                        $comments .= $no.'.'. $eVal->arr[1]->str[$i].'</br>';
                                                         }*/
                                                                                        $id[] =   $eVal->str[0];
                                                                                        $project_id[] =  $eVal->str[1];
                                                                                        $title[] = $eVal->str[2];
                                                                                        $urllink[] =  $eVal->arr->str[1];
                                                                                        $desc[] =  $eVal->str[4];
                                                                                        $cat[] =  $eVal->str[5];
                                                                                       /* $comment[] =  (array) $comments ;*/
                                                if( $eVal->str[5]=='quality'){$count_qa=$i++;}
                                                else{$count_wo=$wo++; }

                                                }

                                        }
                               }
                        }
                }

        }
        }

 $pageURL = 'http';
 if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
 $pageURL .= "://";
$pageURL .= $_SERVER["SERVER_NAME"];

?>
                <div class="title_med2 workorders_filter">
                                <INPUT TYPE="hidden" ID="requestTypeFilter" VALUE"" />
                                        <label for="project_status_filter" style="color: #fff;float: left; margin-top: 10px; font-size: 15px;" id="project_status_filter_label"><?php echo $result_found;?> Search results for "<?php echo  ucfirst($query); ?>"</label>
                                        </div>
                <div id='search_wrapper' class='search_wrapper'>
                <div id='search_results_wrapper' class='search_results_wrapper' style='margin-top:20px;'>
                       <?php if ($result_found > 0){?> <div class='search_results_nav'>
                               <ul>
                                        <li class='active'><a href='#'>All</a></li>
                                        <li><input type="hidden" name="search_text_defect" id="search_text_defect" value="<?php echo $query; ?>"/><a href='#' onclick="load_defect_search();">Defects (<?php echo $count_qa+1;?>)</a></li>
                                        <li><a href='#' onclick="load_workorder_search();">Work Orders(<?php echo $count_wo+1;?>)</a></li>
                                </ul>
                        </div><!-- END search_results_nav -->
                        <div class='search_results_content'><div id="wrapper">
                        <div id="paging_container7">
                                <ul class="content">
<?php


for($i =0 ; $i<count($id); $i++){
if($cat[$i][0]=='quality'){$link = $pageURL.'/quality/index/edit/?defect_id=';$text='DEFECTS';}else{$link = $pageURL.'/workorders/index/edit/?wo_id=';$text='WORKORDERS'; }?>
                                <li> <div class='search_result'>
                                        <h2><a href='<?php echo $link.$id[$i][0]; ?>'><span class='search_txt'  style="color: #358FCE;"><?php echo ucfirst(substr($title[$i][0],0,70));if(strlen($title[$i][0])>70){echo '...';}?></a></span></h2>
                                        <span class='defect_url'><span class='defect_txt'><?php echo $text; ?></span><a href='<?php echo $link.$id[$i][0]; ?>'><?php echo $link.$id[$i][0]; ?></a></span>
                                        <p class='defect_desc'><?php echo  ucfirst(substr($desc[$i][0],0,300));if(strlen($desc[$i][0])>300){echo '...';}?></p>
                                </div> <!-- END search_result --></li>
<?php } ?></ul>
<div class="page_navigation"></div>
                        </div>



                </div>


                        </div><!-- END search_results_content --> <div class="search_results_content_defect"></div>  <div class="search_results_content_wo" ></div>
                <?php } ?>
                </div> <!-- END search_results_wrapper -->

<script type="text/javascript">
			$(document).ready(function(){
				$('#paging_container7').pajinate({
					num_page_links_to_display : 3,
					items_per_page : 10
				});
			});		



function load_defect_search(){
var p = "defect"; 
var option = 'Defect';
var search_text = $("input#search_text_defect").val();
var dataString = 'search_text='+ search_text + '&search_par=' +option + '&p=' +p;  
 $.ajax({
    type: "POST",
    url: "_ajaxphp/search_ajax.php",
    data: dataString,
    success: function(msg) {
      $('.search_results_content_defect').css({display:'block'});
      $('.search_results_content_defect').html(msg) }
     });
}
           

function load_workorder_search(){
$('.search_results_content').css({display:'none'});
$('.search_results_content_defect').css({display:'none'});
var option = 'WorkO';
var search_text = $("input#search_text_defect").val();
var dataString = 'search_text='+ search_text + '&search_par=' +option;
 $.ajax({
    type: "POST",
    url: "_ajaxphp/search_ajax.php",
    data: dataString,
    success: function(msg) {
      $('.search_results_content_wo').css({display:'block'});
      $('.search_results_content_wo').html(msg) }
     });
}
 
		</script>

