<script type="text/javascript">
 google.load("visualization", "1", {packages:["corechart"]});
 
  var dataSet = [
        ['Date', 'Request', 'Problem', 'Outages'],
        ['10-10-2014', 20, 10, 20],
        ['10-11-2014', 20, 30, 10],
        ['10-12-2014', 20, 10, 10],
        ['10-13-2014', 20, 30, 10],
        ['10-14-2014', 20, 30, 10],
        ['10-15-2014', 20, 30, 10],
      
        ];

  // The first chart

  google.setOnLoadCallback(woFrequencyGraph); 
  function woFrequencyGraph() {
    var data = google.visualization.arrayToDataTable( dataSet );

    var options = {
      title: "Workorder Frequency",
      vAxis: {title: 'total', maxValue: 100},  // sets the maximum value
      backgroundColor: {strokeWidth: 2 },  // to draw a nice box all around the chart
      isStacked: 'true'                    //  = rowstacked in gnuplot
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('chart_div1'));
    chart.draw(data, options);
  }
  
  
  
  
    google.setOnLoadCallback(woStatusGraph);
    function woStatusGraph() {
      var data = google.visualization.arrayToDataTable([
        ["Element", "Tickets", { role: "style" } ],
        <?php if(ISSET($this->status_type['New'])) : ?>
        ["NEW", <?php echo $this->status_type['New'] ?>, "#f7eccd"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['Progress'])) : ?>
        ["In-Progress", <?php echo $this->status_type['Progress'] ?>, "#f9decd"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['Fixed'])) : ?>
        ["Fixed", <?php echo $this->status_type['Fixed'] ?>, "#DAE7B2"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['Hold'])) : ?>
        ["On-Hold", <?php echo $this->status_type['Hold'] ?>, "#DDF2FF"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['Need'])) : ?>
        ["Need More Info", <?php echo $this->status_type['Need'] ?>, "#DEE3FF"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['Feedback'])) : ?>
        ["Feedback Provided", <?php echo $this->status_type['Feedback'] ?>, "#DPP3FF"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['rejected'])) : ?>
        ["Rejected", <?php echo $this->status_type['rejected'] ?>, "#EBCBCC"],
        <?php endif; ?>
        <?php if(ISSET($this->status_type['reopend'])) : ?>
        ["Reopend", <?php echo $this->status_type['reopend'] ?>, "#EOJBCC"],
        <?php endif; ?>
		
      ]);

      var view = new google.visualization.DataView(data);
      view.setColumns([0, 1,
                       { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                       2]);

      var options = {
        title: "Workorder Dashboard Graph View",
        width: 900,
        height: 400,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
        backgroundColor: {strokeWidth: 2 }
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
      chart.draw(view, options);
  }
  
  <?php if(count($this->assigned_to) > 0): ?>
  <?php $i = 1; ?>
   google.setOnLoadCallback(woAssignedTo);
    function woAssignedTo() {
      var data = google.visualization.arrayToDataTable([
        ["Element", "Tickets", { role: "style" } ],
        <?php foreach($this->assigned_to as $assinged_key => $assigend_val): ?>
        <?php if($i > 10){
                break;
            }
        $i++ ?>
        <?php $dlId = WoDisplay::getLHUsersObj($assinged_key); ?>
        ["<?php echo $dlId['user_name']  ?>", <?php echo $assigend_val ?>, "#f7eccd"],
        <?php endforeach; ?>
		
      ]);

      var view = new google.visualization.DataView(data);
      view.setColumns([0, 1,
                       { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                       2]);

      var options = {
        title: "Workorder Assigned To Graph View",
        width: 900,
        height: 400,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
        backgroundColor: {strokeWidth: 2 }
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_assignedTo"));
      chart.draw(view, options);
  }
  
  <?php endif; ?>
  </script>
  
  <?php //print_r($this->status_type) ?>
    <div class="title_med workorders_filter">
        <div id="list_view" style="float: right; margin: 0pt; position: absolute; right: 12px; top: 8px;padding-right: 11px">
        <a style="padding-right: 6px;" title="Calendar View" href="/workorders/index/calendarview">
            <img width="23" height="23" alt="Calendar View" src="/_images/cal_active.png">
        </a>
         <a style="padding-right: 6px;" title="List View" href="/workorders">
            <img width="23" height="23" title="List View" alt="List View" src="/_images/list_active.png">
        </a>
         <img width="23" height="23" title="Graph View" alt="Graph View" src="/_images/graph_image.jpg">
        </div>
    </div>
    <div id="wo_containter" class="workorders_container">
        <div id="columnchart_values" style="padding-bottom: 10px; padding-left: 28px; padding-right: 10px;padding-top: 10px;width: 900px; height: 400px;"></div>
        
        <br/>
        <div id="columnchart_assignedTo" style="padding-bottom: 10px; padding-left: 28px; padding-right: 10px;padding-top: 10px;width: 900px; height: 400px;"></div>
        <br/>
       <div id="chart_div1" style="padding-bottom: 10px; padding-left: 28px; padding-right: 10px;padding-top: 10px;width: 900px; height: 400px;display:none;"></div>
    
    </div>
