                    <?php 
					$eventId = (int)$_GET['event_id'];
                    $result=EventDisplay::calenderviewajax($eventId);
                    if (count($result)>0){
                    ?>
                    
                    	<ul <?php if(strtotime($result['est_end_datetime'])> time()):?>class="event_list_old"<?php else:?>class="event_list"<?php endif;?> style="background-color: #F0F0F0;">
                        	<li style="background-color: #FFFFFF;">
                            	<div class="event_left_section" style="width: 200px;margin-left:2px;">
                            	
                                	<?php if(date("Y-m-d",strtotime($result['est_start_datetime']))==date("Y-m-d",strtotime($result['est_end_datetime'])))
                                	{?>
                                	<div class="event_date" style="font-size: 16px;">
                                	<?php	echo date("M d, Y",strtotime($result['est_start_datetime']));
                                	}
                                	elseif(date("Y",strtotime($result['est_start_datetime']))!=date("Y",strtotime($result['est_end_datetime'])))
                                	{?>
                                	<div class="event_date" style="font-size: 13px;">
                                	<?php
                                		echo date("M d, Y",strtotime($result['est_start_datetime'])).' - '.Date("M d, Y",strtotime($result['est_end_datetime']));
                                	}
                    				elseif(date("Y-m",strtotime($result['est_start_datetime'])) == date("Y-m",strtotime($result['est_end_datetime'])))
                                	{?>
                                	<div class="event_date" style="font-size: 16px;">
                                	<?php
                                		echo date("M d",strtotime($result['est_start_datetime'])).' - '.Date(" d, Y",strtotime($result['est_end_datetime']));
                                	}
                    				elseif(date("Y",strtotime($result['est_start_datetime']))== date("Y",strtotime($result['est_end_datetime'])))
                                	{?>
                                	<div class="event_date" style="font-size: 16px;">
                                	<?php
                                		echo date("M d",strtotime($result['est_start_datetime'])).' - '.Date("M d, Y",strtotime($result['est_end_datetime']));
                                	}
                    				
                                	else{?>
                                	<div class="event_date" style="font-size: 16px;">
                                	<?php
                                		echo date("M d",strtotime($result['est_start_datetime'])).' - '.Date("M d, Y",strtotime($result['est_end_datetime']));
                                	}?></div>
                                	<div class="past_event"><?php if(strtotime($result['est_end_datetime'])<time()):?> Past Event<?php endif;?></div>
	                                <div class="event_status" style="margin-left:2px;"><b>Status:</b> <?php echo EventDisplay::getEventStatusType($result['status']);?></div>
                                </div>
                                
                                                            
	                              <?php if(strtotime($result['est_end_datetime'])< time()):?>
		                          <div class="event_center_section" style="width:350px;margin-top: 23px;">
		                          <?php else:?>
		                          <div class="event_center_section" style="width:350px;">
		                          <?php endif;?>
                                    <div class="event_name pointer" <?php if(strtotime($result['est_end_datetime'])<time()):?>style="color: #358FCE;"<?php endif;?> onClick="window.location = '/events/index/create/?eId=<?php echo $result['id']?>';" title="<?php echo Util::htmlEntityTitle($result['title'], 0,30);?>" style="color: #358FCE;" ><?php echo Util::calTitle($result['title'], 0,30);?></div>
                                    <div class="event_company" title="<?php echo EventDisplay::getCompanyName($result['company_id']); ?>" ><?php echo Util::calTitle(EventDisplay::getCompanyName($result['company_id']),0,15);?> | <span class="event_hour"><?php echo date("h:iA",strtotime($result['est_start_datetime']))?> - <?php echo date("h:iA",strtotime($result['est_end_datetime']))?> EST</span></div>   
                                    <div class="event_description">
                                    <?php $arrs = Util::moreOrLessDescription($result['body']);?>
                              			<div id="shortDesc<?php echo $result['id']?>"><?php echo $arrs['short']?><a href="/events/index/create/?eId=<?php echo $result['id']?>"> ...See event details</a></div>
                             		</div>
                                </div>
                              <div class="event_right_section" <?php if(strtotime($result['est_end_datetime'])<time()):?>style="margin-top:19px;"<?php endif;?>>
                              <div class="event_actions" style="padding-left:80px;">
                              <?php if(($result['requested_by']==$this->userId) OR  ($this->editEventFlag == true)):?>
                                 <button onClick="window.location = '/events/index/create/?eId=<?php echo $result['id']?>';"><span>Edit Event</span></button>
                              <?php endif;?>   
                                 <button  onClick="window.location = '/events/index/create/?eId=<?php echo $result['id']?>';"><span>Event Details</span></button>
                              </div>
                                    <div class="event_company_affected" <?php if(strtotime($result['est_end_datetime'])< time()) : ?>style="padding-top: 29px;"<?php endif;?>>
                                        <?php
                                          if(!empty($result['affected_company_list'])):
                                          $affected_company = explode(",",$result['affected_company_list']);
                                          
                              ?>
                                 <p>Affected company <?php if(count($affected_company)>8):?><a href="/events/index/create/?eId=<?php echo $result['id']?>" class='aText'>(more)</a><?php endif;?>:</p>
                                 <ul id="aff_companies" style="margin-left:2px;width:140px;">
                                  
  									<?php for($i=0;$i<count($affected_company) && $i<=3;$i++):?>
                                       <?php $companyName = (strlen(EventDisplay::getCompanyName($affected_company[$i])) > 20)? substr(EventDisplay::getCompanyName($affected_company[$i]),0,18)."..":EventDisplay::getCompanyName($affected_company[$i]);
                                        ?> 
                                      <li style="width:180px;">&bull; <span title="<?php echo EventDisplay::getCompanyName($affected_company[$i])?>" style="color:#6b6b6b;margin-left: 5px;"><?php echo $companyName ?></span></li>
                                      
                                      <?php endfor;?>
                                      
                                      <?php if(count($affected_company)>4):?>
                                          </ul>
                                          <ul id="aff_companies" style="margin-left:2px;width:140px">
                                      	<?php for($i=4;$i<count($affected_company) && $i<8;$i++):?>
                                            <?php $companyName2 = (strlen(EventDisplay::getCompanyName($affected_company[$i])) > 20)? substr(EventDisplay::getCompanyName($affected_company[$i]),0,18)."..":EventDisplay::getCompanyName($affected_company[$i]); ?>                           
                                      		<li style="width:180px;">&bull; <span title="<?php echo EventDisplay::getCompanyName($affected_company[$i])?>" style="color:#6b6b6b;margin-left: 5px;"><?php echo $companyName2;?></span></li>
                                                                        
                                 		<?php endfor;?>
                                      		
                                      <?php endif;?>
                                      </ul>
                               	<?php endif;?>
                                </div>
                                </div>
                                <?php 
                               // if($_GET['slider_date']== date("Y-m", strtotime($result['est_start_datetime'])))
                                //{
                                $divId = "#event_specifics".$this->selectedYear;
                                $divid1="#events_list_container".$this->selectedYear;
                                //}
                                //else{
                                	//$divId = "#event_specifics".date("Y-m", strtotime($result['est__datetime']));
                                //}
                                ?>
                                <?php if(strtotime($result['est_end_datetime'])< time()){
                                	$closeBtnCss = 'style="top:49px"';
                                }else{
                                	$closeBtnCss;
                                }?>
                                
                                <a href="javascript:void(null);" onclick="$('<?php echo $divId ;?>').hide();$('<?php echo $divid1 ;?>').hide();" class="close_btn" <?php echo $closeBtnCss ?>>Close</a>

                            </li>
                        </ul>
<?php } ?>
