<!-- Comment Box block -->
		<div class="content" id="comment_box">
		<div style="margin:10px;height:10px;"></div>
			<div class="workorder_content_col3" style="padding-left: 17px;">
				<div class="main_bucket_container">
					<div class="main_bucket_title"><h4 id="number_of_comments">Comments (<?php echo (count($this->commentInfo) == 0)?0:count($this->commentInfo) ?>)</h4></div>
						<div class="main_bucket_content">
							<ul class="comments" id="comments_list">
							<?php 
							//p($this->commentInfo);
							$pattern = "/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/";
							if(count($this->commentInfo) > 0):
								foreach($this->commentInfo as $k => $commentVal):
									/*$comment = $commentVal['comment'];
									$text_string = preg_replace($pattern, "<a href=\"\\0\"?phpMyAdmin=uMSzDU7o3aUDmXyBqXX6JVQaIO3&phpMyAdmin=8d6c4cc61727t4d965138r21cd rel=\"nofollow\" target='_blank'>\\0</a>",htmlentities($comment,ENT_NOQUOTES, 'UTF-8'));
									$text_string = nl2br($text_string)*/;
									$text_string = Util::escapeString($commentVal['comment']);
									/*$comment_date_time_part = explode(" ", $commentVal['date']);
									$comment_date_part = explode("-", $comment_date_time_part[0]);
									$comment_time_part = explode(":", $comment_date_time_part[1]);*/	
									$where = " id = ".$commentVal['user_id'];									
									$comment_user_data = EventDisplay::getTableData('users', '*',$where);
									//p($comment_user_data);
								?>
							<li>
								<img src="<?php echo $comment_user_data['user_img'] ?>" class="comment_photo" />
								<div class="comment_body">
									<p><strong><?php echo ucfirst($comment_user_data['first_name']) .' ' .ucfirst($comment_user_data['last_name']) ?></strong><br>
									<em><?php echo @date("D M j \a\\t g:i a", strtotime($commentVal['date'])) ?></em></p>
								     <p><?php echo $text_string?></p>                                                 
								</div>
							</li>
						<?php endforeach;?>
						<?php endif;?>	
						</ul>
					<ul class="comment_field_container">
						<li><label id="cmt_box" for="comment" class='event_label'  style="width:130px;text-align:left;"">Add a comment:</label></li>
						<li><textarea name="comment" id="comment" class="field_large" style="width:450px;"></textarea></li>
					</ul>
					<div class="new_comment_actions"><button class="secondary" onClick="return submitComment(); return false;"><span>Submit Comment</span></button></div>
						<div class="clearer"></div>
					</div>
				</div>
			</div>
		</div>
