<script type="text/javascript">
	$(document).ready(function(){
		$(".past_events_img").tooltip({position: ['center', 'right']});
		$(".upcoming_events_img").tooltip({position: ['center', 'right']});
		$(".past_left_events_img").tooltip({position: ['center', 'left']});
		$(".upcoming_left_events_img").tooltip({position: ['center', 'left']});
		$(".past_left_events_imgg").tooltip({position: ['center', 'left']});
		$(".upcoming_left_events_imgg").tooltip({position: ['center', 'left']});
		
		$(".upcoming_events_imgg").tooltip({position: ['center', 'right']});
		$(".past_events_imgg").tooltip({position: ['center', 'right']});
		$("#form_success").tooltip({position: ['top', 'center']});
		});

			function slider(slider,slider_date,event_id,year){
				$('.events_list_calenderviewajax').hide();
				$('.event_specifics').hide();
				//$('#save_buttons_dimmer').css('display','block');
				$('.event_specifics').css('display','none');
				var slider = slider;
				$.ajax({
					type: "GET",
					url: "/events/index/calendarviewajax",
					data:{slider:slider,slider_date:slider_date,event_id:event_id,year:year,p:'ajax'},
					
					success: function(msg) {
						$('#event_specifics'+slider_date).slideToggle("slow");
						$('#event_specifics'+slider_date).html(msg);
						$('#events_list_container'+slider_date).css('display','block');
						$('html,body').animate({scrollTop: $('#event_specifics'+slider_date).offset().top},'slow');
					}

				});
			}
		/*$("button").click(function () {
		$(".event_specifics").slideToggle("slow");
		});*/
		
		//
		function hidediv(){
		$('.tooltip').hide();	
		//$('.events_list_calenderviewajax').css('display','none');	
		}
		
		function showMore(id){
		var obj ="fullDesc"+id;
		document.getElementById(obj).style.display='';
		
		var obj1 ="shortDesc"+id;
		document.getElementById(obj1).style.display='none';   
		
		}
		function showListing(){
		$('.showListAll').css('display','');
		$('#showList').css('display','none');
		
		}
		
		
		
		var id;
		
		function showMore(id){
		var obj ="fullDesc"+id;
		document.getElementById(obj).style.display='';
		
		var obj1 ="shortDesc"+id;
		document.getElementById(obj1).style.display='none';	
		}
		
		function showLess(id){
		var obj ="fullDesc"+id;
		document.getElementById(obj).style.display='none';
		
		var obj1 ="shortDesc"+id;
		document.getElementById(obj1).style.display='';	
		}
		
		
		function showListing(id){
		$('.showListAll'+id).css('display','');
		$('#showList'+id).css('display','none');
		
		}
		
		function showListingLess(id){
		$('.showListAll'+id).css('display','none');
		$('#showList'+id).css('display','');
		
		}

</script>
<?php if($_REQUEST['p']!='ajax'){ ?>
	<script type="text/javascript">
		$(document).ready(function(){
		$('#year_filter').change(function(){
		$('#save_buttons_dimmer').css('display','block');
		$('#wo_dimmer_ajax').css({display:'block'});
		//alert('year_filter');
		var year_filter = $('#year_filter').val();
		$('#year_filter').val(year_filter);
		$('#year_filter').val();
		if(year_filter != null){	
		var company_filter = $('#company_filter').val();
		$('#company_filter').val(company_filter);
		$('#company_filter').val();
				//alert(company_filter);
			$.ajax({
			type: "GET",
			url: "/events/index/calendarview",
			data:{year:year_filter,comp_id:company_filter,p:'ajax'},
			success: function(msg) {
				//alert(msg);
				$('#save_buttons_dimmer').css('display','none');
				$('#wo_dimmer_ajax').css({display:'none'});
				$('#calender_ajax').html(msg);
			}});
			}else{
				$('#save_buttons_dimmer').css('display','none');
				$('#wo_dimmer_ajax').css({display:'none'});
				$('#calender_ajax').html(msg);
			}
			});
		
		$('#company_filter').change(function(){
		$('#save_buttons_dimmer').css('display','block');
		$('#wo_dimmer_ajax').css({display:'block'});
		var year_filter = $('#year_filter').val();
		$('#year_filter').val(year_filter);
		$('#year_filter').val();
		//alert('company_filter');
		var company_filter = $('#company_filter').val();
		$('#company_filter').val(company_filter);
		$('#company_filter').val();
		if(year_filter != null){		
		//alert(company_filter);
			$.ajax({
			type: "GET",
			url: "/events/index/calendarview",
			data:{year:year_filter,comp_id:company_filter,p:'ajax'},
			success: function(msg) {
				//alert(msg);
				$('#save_buttons_dimmer').css('display','none');
				$('#wo_dimmer_ajax').css({display:'none'});
				$('#calender_ajax').html(msg);
			}
			});
			}else{
				$('#save_buttons_dimmer').css('display','none');
				$('#wo_dimmer_ajax').css({display:'none'});
				$('#calender_ajax').html(msg);
			}
			});
			
			
		});
</script>
<!--[if gte IE 6]>
<style>
.event_company_affected{
			padding-top: 10px !important;
			}
</style>
<![endif]-->
<div class="events_content_container" >

				<div class="main_actions_event" style="margin:0px;padding:3px 0 32px;">
					
					<button onClick="window.location = '/events/index/create/';" style="margin:0px;"><span>create new event</span></button>
                    
				</div>
						
                
                
                <div class="section_title">
                	<div class="title" style="padding-left:12px;">Events</div>
                    <div id="list_view" >
                       <span style='padding-right: 8px;'><img src="/_images/cal_dis_03.png" alt="Calendar View" width="23" height="23" /></span>
                       <span style='padding-right: 6px;'><a href="/events/index/listview" title="List View"  ><img src="/_images/list_active.png" alt="List View"  title="List View" width="23" height="23" /></a></span>
                	</div>

                </div>
                


				<div class="title_med events_filter">
					<label for="year_filter" id="year_filter_label" style="margin-left: 10px;">&nbsp;Year</label>
					<select id="year_filter" name='year_filter' style="margin:10px 26px 0 8px;">
 						<?php echo $this->yearList; ?>
					</select>
					<label for="company_filter" id="company_filter_label">Affected Company</label>
					<select id="company_filter" style="margin:10px 26px 0 8px;">
					<option value="-1">Show All</option>
					<?php
							$count = 1;
							$rsCompanyHtml = array(); 
							$rsCompanyHtml = EventDisplay::getCompanyListHTML(); ?>
							
								<?php if(count($rsCompanyHtml) > 0):?>
								<?php foreach($rsCompanyHtml as $comkey => $compVal):?>
								<option value="<?php echo $compVal['id'] ?>">
								<?php echo $compVal['name'] ?></option>
										<?php  
							$count++;
								
							?>
							<?php endforeach; ?>	
							<?php endif; ?>
						
					</select>
                    
                    <div class="events_icons">
                    	<div class="multiple_icon">Multiple Events in 1 Day</div>
                        <div class="upcoming_icon">Upcoming Events</div>
                        <div class="past_icon">Past Events</div>
                    </div>
					
				</div><?php } ?>
	<div id="calender_ajax">
            <?php $count_event =0;
        	  $count_event = count($this->evntInfo);
        if ($count_event>0){?>
        
                <div class="recent_events">
                	<h3>Upcoming Events:<?php //print_r($this->evntInfo);?></h3>
                    <p class="time_based">Based on Eastern Time</p>
                    <ul class="event_list events_list_container shadowm"><?php
					$i=0;
					foreach ($this->evntInfo as $htmls=>$htmlvalue):
					if($i==2)
					{echo '<li class="last">';}
					else{ echo '<li>';}
							   echo '<div class="event_date">'.date("M d, Y",strtotime($htmlvalue['est_start_datetime'])).'</div>
                            <div class="event_name" ><a onclick=slider("'.date("Y-m-d",strtotime($htmlvalue['est_start_datetime'])).'","'.date("Y-n",strtotime($htmlvalue['est_start_datetime'])).'","'.$htmlvalue['id'].'","'.date("Y-n",strtotime($htmlvalue['est_start_datetime'])).'") href=javascript:void(null); title="'.Util::htmlEntityTitle($htmlvalue['title']).'" alt="'.$htmlvalue['title'].'" style="text-decoration:none;color:#358fce">'.util::calTitle($htmlvalue['title'], 0,30).'</a></div>
                            <div class="event_company" style="color:#6f6f6f" title="'.EventDisplay::getCompanyName($htmlvalue['company_id']).'">'.Util::calTitle(EventDisplay::getCompanyName($htmlvalue['company_id'])).'</div>
                        </li>';
						$i++;
			endforeach;
			?>
                    </ul>
                </div>
                <!--==| END: recent_events |==-->
     <?php } ?>				
<div class="event_calendars" ><ul>
<?php 
$eventArray  = EventDisplay::getYearEvents($this->calendar_yr,$this->comp_id);
for ($i=1;$i<=12;$i++)
{
echo EventDisplay::draw_calendar($i,$this->calendar_yr,$eventArray);
} ?>
</ul></div>
</div>
<div class="wo_dimmer" id="save_buttons_dimmer" style="display:none;"></div>  
<div class="wo_save_box" id="wo_dimmer_ajax" style="display: none;"><img src="/_images/ajax-loader.gif" alt="ajax-loader"/></div>
