<?php
if(isset($this->mobileuser) && $this->mobileuser){
	echo $this->layout()->content;
}else{

	global $USER_ACCESS;
	global $USER_ACCESS_MENU;

	$menu_array = $_SESSION['menu_array'];	
	
	//substring it to get rid of beginning /
	$menu_url = explode("/", substr($_SERVER['REQUEST_URI'], 1));
	$_controller = $menu_url[0];
	$_action = $menu_url[2];
	if($_controller == "login") {
		$login_class = " content_container_login";
	} else {
		$login_class = "";
	}


	include "_includes/head.php";
	include "_includes/settings_bar.php";
	include "_includes/navigation.php" ;
	
	
?>
	<!--==| START: Content |==-->
	<div class="wrapper">
		<div class="content_container<?PHP echo $login_class; ?>">

	
		
			<!-- This next call will now include any content that was generated in the
			dispatching of a controllers action (or series of actions).  -->
			<?PHP

			if($menu_url[0] == "admin") {
				include "_includes/adminNavigation.php";
			}
			else
			{
				echo $this->layout()->content;
			}
			?>
		
		</div>
	</div>
	<!--==| END: Content |==-->	
	
	<div id="blur" class="blur jHelperTipClose"></div>
<?PHP
	include "_includes/footer.php";
}
?>