
	<?php $userInfo = EventDisplay::getRequestorInfo($this->escape($this->user_id)); ?>
	<?php //p($userInfo);?>
	<div class="side_bucket_title">Requestors Information</div>
		<div class="side_bucket_content">
			<img src="<?php echo $userInfo[0]['user_img'] ?>" id="requestor_photo" class="requestor_photo">
			<ul class="requestor_fields">
				<li>
					<label for="requestor_name">Requested By:</label>
					<input class="field_small readonly" name="requestor_name" id="requestor_name" type="text" value="<?php echo $userInfo[0]['full_name'] ?>" readonly />
				</li>
				<li>
					<label for="requestor_email">E-mail:</label>
					<input class="field_small readonly" name="requestor_email" id="requestor_email" type="text" value="<?php echo $userInfo[0]['email'] ?>" readonly />
				</li>
				<li>
					<label for="requestor_phone">Phone:</label>
					<input class="field_small readonly" name="requestor_phone" id="requestor_phone" type="text" value="<?php echo $userInfo[0]['phone_office'] ?>" readonly />
				</li>
			</ul>
			<div class="clearer"></div>
		</div>
