<?PHP
	/*
	Base Zend index file loaded for the index.php file
	*/
	//include('ControlTower.inc');
	//echo "Hello World Control Tower Index.phtml at application/modules/controltower/views/scripts/index - ";
	
	//$sections = CtDisplay::getSectionHTML();
?>
<?PHP
	/*
	<!--=========== START: COLUMNS ===========-->
		
			<!--==| START: Bucket |==-->
			<div class="title_lrg">
				fdasfsadf
				<?php 
					//include "_includes/ct_top_newproject.php" 
				?>
			</div>
			<!--==| END: Bucket |==-->
		
			<!--==| START: Bucket |==-->
			<div class="full_content_container_noscroll control_tower_main">
				
				<div class="contentCol">
					<div class="leftCol">
						asdfasdfasdffads
						<?php
							//self::leftNav();
							//include "_includes/ct_left_tabs.php" 
						?>
					</div>
					<div class="rightCol">
						sdafadsfasdf
						<?php 
							//include "_includes/ct_drafting_actions.php" 
						?>
						<div class="inside textEdit">
							<img src="_images/tmpTextEdit.gif">
						</div>
					</div>
					<div style="clear: both;"></div>
				</div>
	
			</div>
			<!--==| END: Bucket |==-->

<!--=========== END: COLUMNS ===========-->
*/
?>