<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="stylesheet" href="/css/blueprint/screen.css" type="text/css" media="screen, projection">
	<link rel="stylesheet" href="/css/blueprint/print.css" type="text/css" media="print">    

	<!--[if IE]><link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?= $this->headTitle("NBCUXD - User Experience Design") ?>
    <?= $this->headScript() ?>
    <?= $this->headStyle() ?>
</head>
<body>
<div class="container quiet">
     <div class="span-24">
     	<div id="header"><?= $this->partial('header.phtml') ?></div>
     </div>
     <div class="span-24">
        <div id="content"><?= $this->layout()->content ?></div>
      </div>
	  <div class="span-24">
         <div id="footer"><?= $this->partial('footer.phtml') ?></div>
      </div>
</div>
</body>
</html>