<input type="hidden" name="adminTitlemsg" id="adminTitlemsg" value="Rally Lighthouse Mapping">
<div class="rightCol" id="form_sec_1" style="display: block;min-height:400px;">
		<?php 
		
		//print_r($this->LhRallyProjects); 
		$lhProjectArray = array();
		$rallyProjectArray = array();
		if(count($this->LhRallyProjects) > 0){
		
			foreach($this->LhRallyProjects as $k => $v){
				$lhProjectArray[] = $v['lh_project_id'];
				$rallyProjectArray[] = $v['rally_project_id'];
			}
		
		}
		
		?>
		
		<div id='requestor_info'></div>
		<table>
		<tr>
			<td>
			<div class="adminSelect">
				<p> Lighthouse Project:</p>
				<select id="lh_project" name="lh_project" class="field_medium" >
					<option value="">--Select Project--</option>
					<?php //print $this->LHProjectHtml; 
					$companyId = false;
					$projects = $this->LHProjectHtml;
					for($i = 0; $i < sizeof($projects); $i++) {
						if($projects[$i]['company'] != $companyId) { ?>
						<optgroup label="<?php echo $projects[$i]['company_name']?>" >
						<?php } ?>
						<?php if(!in_array($projects[$i]['id'],$lhProjectArray)){ ?>
						<option value="<?php echo $projects[$i]['id'] ?>" > 
						<?php	echo $projects[$i]['project_code'].' - '.$projects[$i]['project_name']; ?>
						</option>
						<?php 
						}
						$companyId = $projects[$i]['company'];
						$nxt = $i+1;
						if($projects[$nxt]['company'] != $companyId) { ?>
							</optgroup>
						<?php }
					}
					
					?>
				</select>
			</div>
			</td>
			<td>
			<div class="adminSelect">
			<p> Rally Project:</p>
			<?php
			
			
			//print "<pre>";
			//print_r($rallyArray);
			?>
			<select id="rally_project" name="rally_project" class="field_medium" >
			<option value="">--Select Rally Project--</option>
			<?php
				$i = 0;
				$temp = '';
				
				foreach($this->rallyArray as $r_key => $r_val){?>
					<optgroup label="<?php echo $r_key ?>">
						
						
				<?php foreach($r_val as $r_key2 => $r_val2){?>
						<?php if(!in_array($r_val2['id'],$rallyProjectArray)){ ?>
						<option value="<?php echo $r_val2['id']; ?>"><?php echo $r_val2['name']; ?></option>
					
						<?php   
							}
							}
						?>
						</optgroup>
					
					<?php } ?> 
				</select>
			</div>
			
			</td>
			
		</tr>
		
	
	</table>
	
	<div >
<br/><br/>
	<p >
		<button style='margin-left:224px;' id="rallyReportbtn" onclick="return mappLHRalyProjectes();"><span>Submit</span></button>
	</p>
	
<br/><br/>
<p></p>
<div style="clear: both;"></div>
<input type="hidden" id="mappCounter" value="<?php echo count($this->LhRallyProjects) ?>">
<div class="mappProj" >	
	<table name="mapProjectData" width="100%"  class="adminTable">
		<tr class="adminTh">
		<th>Lighthouse Project</th>
		<th>Rally Project</th>
		<th>Delete</th>
		</tr>
		<?php
			if(count($this->LhRallyProjects) >0){
	
			 foreach($this->LhRallyProjects as $key => $LH_val){   ?>
			<tr id="tr_<?php echo trim($LH_val['id']); ?>" class="adminTr">
			<td width="40%" ><?php echo $LH_val['lh_project']; ?></td>
			<td width="40%"  ><?php echo $LH_val['ra_project']; ?></td>
			<td width="20%" style="text-align:center;"><img class="dropProject" src="/_images/b_drop.png" alt="drop" onclick="deleteRallyProject(<?php echo $LH_val['id'] ?>);"></td>
			</tr>
		
		
		<?php } ?>
	<?php } ?>
	</table>
</div>

<div class="message_required">
	<p></p>
	<div style="clear: both;"></div>
		<div class="duplicate_buttons">
		<button onClick="$('.message_required').css({display:'none'}); return false;"><span>OK</span></button>
	<div style="clear: both;"></div>
</div>					
<div style="clear: both;"></div>
