<html>
<body>
<?php 

?>
<b>Requestor:</b> <?php echo $this->eventInfo['requestedBy'] ?><br/><br/>
<b>Brand:</b> <?php echo $this->eventInfo['brand'] ?><br/><br/>

<b><?php echo $this->eventInfo['currentUserInfo'] ?></b> has been deleted the event <a href="<?php echo BASE_URL ?>/events/index/create/?eId=<?php echo $this->eventInfo['event_id'] ?>"><?php echo $this->eventInfo['event_id'] ?></a>
<hr>
<br/>
<b>Event Description:</b> <?php echo Util::escapeString($this->eventInfo['desc']) ?><br />

</body>
</html>
