<?php if ($this->workorder) :?>
<p>Are you sure that you want to delete the Workorder?
  <p>BaseCamp ID : <?php echo $this->escape($this->workorder->bcid); ?> 	
  <p>Title : <?php echo $this->escape($this->workorder->title); ?> 
  <p>Description: <?php echo $this->escape($this->workorder->body); ?>
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->workorder->id; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>
<?php else: ?>
<p>Cannot find workorder.</p>
<?php endif;?>
