<div class="column span-14"><img src ="/images/logo.gif"></div>
<div class="column span-2 "> <?php echo $_SESSION['basecamp']['isClient'] ? '[CLIENT]':'[STAFF]'; ?> </div>
<div class="column span-7 last">
	 <?php echo $_SESSION['basecamp']['username'] ; ?> | My Profile | <a href="<?php echo "$this->baseUrl/logout" ?>" >Logout</a>
</div>
<div class="span-24 last">
<p align="center">

<!--
			<a href="<?php echo "$this->baseUrl/dashboard" ?>" >Dashboard | </a>&nbsp;
			<a href="<?php echo "$this->baseUrl/controltower" ?>" >Control Tower | </a>&nbsp;
			<a href="<?php echo "$this->baseUrl/launchcalendar" ?>" >Launch Calendar | </a>&nbsp;
			<a href="http://tools.nbcuxd.com/resourceplanner">Resource Planner</a>&nbsp;
-->
			<a href="<?php echo "$this->baseUrl/qaworkorders" ?>" >QA Work Orders</a>&nbsp;
</p>
</div>
