<style>
<!--
.error {
/*   padding-left: 91px;*/
  padding-bottom: 2px;
  font-weight: bold;
  color: #EA5200;
}
-->
</style>
<!--==| START: Content |==-->
<div class="login_box_container">
	<div class="login_box">
		<div class="login_box_inner">
		<div class="error_row"><?php echo $this->error; ?></div>
		<?php if(empty($this->error) && isset($_POST['submit_login'])) {
				echo '<div class="error_row">Incorrect Username or Password!</div>';
		}?>
		<form action="/login/" method="post" name="<?php echo $this->loginform ?>" id="<?php echo $this->loginform ?>" autocmplete='off'>
		<input type="hidden" name="submit_login" value="submit_login" />
				<div class="form_row"><label class="login_label">User Name:</label><input class="login_field" type="text" id="lh_username" name="lh_username" /></div>
				<div class="form_row"><label class="login_label">Password:</label><input class="login_field" type="password" id="lh_password" name="lh_password" /></div>
				<?php if($this->loginform == 'login_form_captcha'):?>
			  <div class="form_row" style="margin-left:50px;"><?php echo $this->recaptcha	?> 
			    </div>
				<?php endif; ?>
				<div class="form_row_offset"><input type="checkbox" name="remember" id="remember"/><label for="remember">Remember me next time.</label></div>
				
			<div class="form_row_buttons"><button  class='secondary' type="submit"  name="submit"  ><span class="login_button">OK</span></button></div>
		</form>
		</div>
	</div>
	<div class="login_help_container">
	<div class="forgot_pass"><a href="<?php echo BASECAMP_HOST;?>/amnesia/forgot_password">Forgot Password</a></div>
	<div class="forgot_pass" style="margin-left:103px;"><a href="<?php echo BASE_URL;?>/login/index/ssologin">SSO Login</a></div>
	<div style="color:#1F96F9;text-decoration:none;float:right;"><?php echo LIGHTHOUSE_VERSION ?></div>  
	<!--<div class="login_help"><a href="">Help</a></div>-->
	</div>
</div>
<!--==| END: Content |==-->
