<p>Your NBCUXD work order was successfully created. 
Our Que Manager will assign the work and you will be e mailed status updates. 
Work orders show up in Basecamp as messages under the  category "Workorders" 
in the referenced Basecamp project. You can view and add comments to 
work orders just as you would any other BaseCamp message thread. 
You, The Que Manager and the assigned NBCUXD resource were automatically added to the notification list, 
so any new comments pertaining to this work order will be copied in an email and sent out.</p>

<p><A HREF="/workorders/index/create">Click here to  Create Another Work Order.</A></p>