<script>
$(document).ready(function(){

	$('#month_filter').change(function(){
	  $('#save_buttons_dimmer').css('display','block');
	  $('#wo_dimmer_ajax').css({display:'block'});

	  var month_filter = $('#month_filter').val();
	  var year_filter = $('#year_filter').val();
	  var company_filter = $('#company_filter').val();
	  var status_filter = $('#status_filter').val();

     
   	   $.ajax({
		   type: "GET",
		   url: "/events/index/listview",
		   data:{month:month_filter,year:year_filter,company:company_filter,status:status_filter,p:'ajax'},
		   success: function(msg) {
		    //alert(msg);
		    //$('#save_buttons_dimmer').css('display','none');
		    $('#wo_dimmer_ajax').css({display:'none'});
		    $('#ajax_wrapper').html(msg);
		   		   	    
		   }
   		});
   	});

	$('#year_filter').change(function(){
	  $('#save_buttons_dimmer').css('display','block');
	  $('#wo_dimmer_ajax').css({display:'block'});

	  var month_filter = $('#month_filter').val();
	  var year_filter = $('#year_filter').val();
	  var company_filter = $('#company_filter').val();
	  var status_filter = $('#status_filter').val();

	

   
 	   $.ajax({
		   type: "GET",
		   url: "/events/index/listview",
		   data:{month:month_filter,year:year_filter,company:company_filter,status:status_filter,p:'ajax'},
		   success: function(msg) {
		    //alert(msg);
		    //$('#save_buttons_dimmer').css('display','none');
		    $('#wo_dimmer_ajax').css({display:'none'});
		    $('#ajax_wrapper').html(msg);
		    
		   		    
		   }
 		});
 	});

	$('#company_filter').change(function(){
	  $('#save_buttons_dimmer').css('display','block');
	  $('#wo_dimmer_ajax').css({display:'block'});

	  var month_filter = $('#month_filter').val();
	  var year_filter = $('#year_filter').val();
	  var company_filter = $('#company_filter').val();
	  var status_filter = $('#status_filter').val();

 
	   $.ajax({
		   type: "GET",
		   url: "/events/index/listview",
		   data:{month:month_filter,year:year_filter,company:company_filter,status:status_filter,p:'ajax'},
		   success: function(msg) {
		    //alert(msg);
		    //$('#save_buttons_dimmer').css('display','none');
		    $('#wo_dimmer_ajax').css({display:'none'});
		    $('#ajax_wrapper').html(msg);
		    
		   		    
		   }
		});
	});

	$('#status_filter').change(function(){
	  $('#save_buttons_dimmer').css('display','block');
	  $('#wo_dimmer_ajax').css({display:'block'});

	  var month_filter = $('#month_filter').val();
	  var year_filter = $('#year_filter').val();
	  var company_filter = $('#company_filter').val();
	  var status_filter = $('#status_filter').val();


	   $.ajax({
		   type: "GET",
		   url: "/events/index/listview",
		   data:{month:month_filter,year:year_filter,company:company_filter,status:status_filter,p:'ajax'},
		   success: function(msg) {
		    //alert(msg);
		    //$('#save_buttons_dimmer').css('display','none');
		    $('#wo_dimmer_ajax').css({display:'none'});
		    $('#ajax_wrapper').html(msg);
		    
		   		    
		   }
		});
	});
	
});

var id;

function showMore(id){
	var obj ="fullDesc"+id;
	document.getElementById(obj).style.display='';
	
	var obj1 ="shortDesc"+id;
	document.getElementById(obj1).style.display='none';	
}

function showLess(id){
	var obj ="fullDesc"+id;
	document.getElementById(obj).style.display='none';
	
	var obj1 ="shortDesc"+id;
	document.getElementById(obj1).style.display='';	
}


function showListing(id){
	$('.showListAll'+id).css('display','');
	$('#showList'+id).css('display','none');
	
}

function showListingLess(id){
	$('.showListAll'+id).css('display','none');
	$('#showList'+id).css('display','');
	
}


var num;
function pageAjax(num){
	  pagenum= num;
	 
	  $('#save_buttons_dimmer').css('display','block');
	  $('#wo_dimmer_ajax').css({display:'block'});

	  var month_filter = $('#month_filter').val();
	  var year_filter = $('#year_filter').val();
	  var company_filter = $('#company_filter').val();
	  var status_filter = $('#status_filter').val();
	  
	  


	   $.ajax({
		   type: "GET",
		   url: "/events/index/listview",
		   data:{month:month_filter,year:year_filter,company:company_filter,status:status_filter,pagenum:pagenum, p:'ajax'},
		   success: function(msg) {
		    //alert(msg);
		    //$('#save_buttons_dimmer').css('display','none');
		    $('#wo_dimmer_ajax').css({display:'none'});
		    $('#ajax_wrapper').html(msg);
		    
		   		    
		   }
		});
}

 </script>
 <style>
<!--

a {
    /*color: #358FCE;*/
    text-decoration: none;
}
-->
</style>

<!--[if gte IE 6]>
<style>
.event_company_affected{
			padding-top: 10px !important;
			}
</style>
<![endif]-->




<div id="ajax_wrapper"><!-- Start ajax div -->

<div class="events_content_container">
			<div style="display: none;" id="wo_dimmer_ajax" class="wo_save_box">
				<img alt="ajax-loader" src="/_images/ajax-loader.gif"/>
			</div>

			<!--==| START: Bucket |==-->
			<div class="main_actions_event" style="margin-left:-4px;padding: 3px 0pt 32px;">
        		<button onClick="window.location = '/events/index/create/';"><span>create new event</span></button>
            </div>
			<!--==| END: Bucket |==-->

			<!--==| START: Bucket |==-->
          	<div class="section_title">
			  	<div class="title" style="padding-left:12px;">Events</div>
			  	<div id="list_view" >
                       <span style="padding-right:8px;"><a href="/events/index/calendarview" title="Calendar View" ><img src="/_images/cal_active.png" alt="Calendar View" width="23" height="23" /></a></span>
                       <span style="padding-right:6px;"><img src="/_images/list_dis_05.png" alt="List View"  title="List View" width="23" height="23"  /></span>
                </div>
	 	  	</div>
			<!--==| END: Bucket |==-->
				
			<!--==| START: Sorting |==-->
			<div class="title_med events_filter">
				<label id="month_filter_label" for="month_filter" style="margin-left: 10px;">&nbsp;Month</label>
                <select id="month_filter" name="month_filter" style="margin:10px 26px 0 8px;">
                   <?php echo $this->monthnameHtml;?>
				</select>
                <label id="year_filter_label" for="year_filter">Year</label>
                <select id="year_filter" name="year_filter" style="margin:10px 26px 0 8px;">
                    <?php echo $this->yearList; ?>
              	</select>
                <label id="company_filter_label" for="company_filter">Affected Company</label>
                <select id="company_filter" name="company_filter" style="margin:10px 26px 0 8px;">	
					<option value="-1">Show All</option>
     				<?php
       					$count = 1;
       					$rsCompanyHtml = array();
       					$rsCompanyHtml = EventDisplay::getCompanyListHTML(); ?>
       
        				<?php if(count($rsCompanyHtml) > 0):?>
        					<?php foreach($rsCompanyHtml as $comkey => $compVal):?>
        					    <?php
        					     if($this->company_id==$compVal['id']):
        					     	$select_company ="selected";
        					     else:
	       					    	$select_company="";
	       					    endif;    					    
        					    ?>
        						<option value="<?php echo $compVal['id'] ?>" <?php echo $select_company;?>>
        						<?php echo $compVal['name'] ?></option>
          						<?php $count++; ?>
       						<?php endforeach; ?> 
       					<?php endif; ?>
        		</select>
                <label id="status_filter_label" for="status_filter">Status</label>
               	<select id="status_filter" name="status_filter" style="margin:10px 26px 0 8px;">
                    <option value="0">Show All</option>	
                    <?php print $this->eventStatus;?>
                </select>
			</div>
			<!--==| END: Sorting |==-->
			<?php if(count($this->data)):?>
			<br />
			<a href="/events/"><img src="/_images/arrow.png" title="Back to Calendar View" >&nbsp;&nbsp;<span style="color:#358FCE;text-decoration:none;font-family:arial;font-size:12px;"><strong>Back to Calendar View</strong></span></a>
          
            <div class="result_label_anual" style="margin-top:10px;margin-left:1px;">
            
            
            There <?php echo $this->totalData<=1?"is":"are"?> <strong><?php print $this->totalData;?></strong> matching <?php echo $this->totalData>1?"events":"event"?> for <?php echo EventDisplay::$monthShortname[$this->month];?> <?php echo $this->year;?></div>
            
            <!--==| START: Events |==-->
          	<div class="events_list_container shadowm" id="events_list_container">
           	  <div class="event_specifics" style="padding-top:0px;">
           	  
           	  <?php //echo"<pre>"; //print_r($this->data); echo "</pre>";?>
               	  <ul style="background-color:#F0F0F0;padding: 0px 0px 5px 5px;" class="event_list gray_bg">
               	 <?php $time = time(); ?>
               	   	  <?php foreach ($this->data as $listdata):?>
               		  <li <?php if(strtotime($listdata['est_end_datetime'])> $time):?>id="item_gray_old"<?php else:?>id="item_gray"<?php endif;?>class="width_item" style="background-color:#FFFFFF;">
                   		  <div class="event_left_section">
                              <div class="event_date"><?php print date("M d, Y",strtotime($listdata['start_date']));?></div>
                              <div class="past_event"><?php if(strtotime($listdata['est_end_datetime'])<$time):?> Past Event<?php endif;?></div>
                              <div class="event_status" style="margin-left:2px;"><b>Status:</b> <?php echo EventDisplay::getEventStatusType($listdata['status'])?></div>
                          </div>
                          <?php if(strtotime($listdata['est_end_datetime'])<$time):?>
                          <div class="event_center_section" style="width:350px;margin-top: 23px;">
                          <?php else:?>
                          <div class="event_center_section" style="width:350px;">
                          <?php endif;?>
                           	  <div class="event_name" style="padding-bottom: 1px;"><a <?php if(strtotime($listdata['est_end_datetime'])<$time):?> style="color: #358FCE;" <?php endif;?> title="<?php echo Util::htmlEntityTitle($listdata['title'])?>" href='/events/index/create/?eId=<?php echo $listdata['id']?>' style="color: #358FCE;"><?php echo Util::calTitle($listdata['title'],0,35);?></a></div>
                              <div class="event_company" style="width:470px; margin-top: -1px;" title="<?php echo EventDisplay::getCompanyName($listdata['company_id']); ?>"><?php echo Util::calTitle(EventDisplay::getCompanyName($listdata['company_id']),0,20);?> | <span class="event_hour"><?php echo Date("h:iA",strtotime($listdata['est_start_datetime']))?> - <?php echo Date("h:iA",strtotime($listdata['est_end_datetime']))?> EST</span></div>   
                              <div class="event_description" <?php if(strtotime($listdata['est_end_datetime'])<$time):?>style="padding-top: 24px;"<?php endif;?>>
                              <?php $arrs = Util::moreOrLessDescription($listdata['body']);?>
                              <div id="shortDesc<?php echo $listdata['id']?>"><?php echo $arrs['short']?><a href="/events/index/create/?eId=<?php echo $listdata['id']?>"> ...See event details</a></div>
                              </div>
                          </div>
                          <div class="event_right_section" <?php if(strtotime($listdata['est_end_datetime'])<$time):?>style="margin-top:19px;"<?php endif;?>>
                       	  <div class="event_actions" style="padding-left:111px;">
                           	  <?php if(($listdata['requested_by']==$this->userId) OR  $this->editEventFlag):?>
                           	   	  	<button style="margin-left:-4px;" onClick="window.location = '/events/index/create/?eId=<?php echo $listdata['id']?>';"><span>Edit Event</span></button>
                              <?php endif;?> 	  
                                  	<button onClick="window.location = '/events/index/create/?eId=<?php echo $listdata['id']?>';"><span>Event Details</span></button>
                              </div>
                              <div class="event_company_affected" <?php if(strtotime($listdata['est_end_datetime'])<$time):?>style="padding-top: 29px;"<?php endif;?>>
                              <?php
                                 if(!empty($listdata['affected_company_list'])):
                                 	$affected_company = explode(",",$listdata['affected_company_list']);
                                          
                              ?>
                             <p>Affected company <?php if(count($affected_company)>8):?><a href="/events/index/create/?eId=<?php echo $listdata['id']?>" class='aText'>(more)</a><?php endif;?>:</p>
                             <ul id="aff_companies" style="margin-left:2px;width:150px;">
                                  
                                    <?php for($i=0;$i<count($affected_company) && $i<=3;$i++):?>
                                    <?php 
                                    
                                    $companyName = (strlen(EventDisplay::getCompanyName($affected_company[$i])) > 20)? substr(EventDisplay::getCompanyName($affected_company[$i]),0,18)."..":EventDisplay::getCompanyName($affected_company[$i]);
                                    
                                    ?>
                                    <li style="width:180px;">&bull; <span title="<?php echo EventDisplay::getCompanyName($affected_company[$i])?>" style="color:#6b6b6b;margin-left: 5px;"><?php echo  $companyName ;?></span></li>
                                     
                                    <?php endfor;?>
                                      
                                      <?php if(count($affected_company)>4):?>
                                      
                                          </ul>
                                          <ul id="aff_companies" style="margin-left:2px;width:150px">
                                      	<?php for($i=4;$i<count($affected_company) && $i<8;$i++):?>

                                                 <?php 
                                    				$companyName2 = (strlen(EventDisplay::getCompanyName($affected_company[$i])) > 20)? substr(EventDisplay::getCompanyName($affected_company[$i]),0,18)."..":EventDisplay::getCompanyName($affected_company[$i]);
                                    
                                    			?>                      
                                      			<li style="width:180px;">&bull; <span title="<?php echo EventDisplay::getCompanyName($affected_company[$i])?>" style="color:#6b6b6b;margin-left: 5px;"><?php echo $companyName2 ;?></span></li>

                                                                        
                                 		<?php endfor;?>                                             		
                                      <?php endif;?>
                                      </ul>
                               	<?php endif;?>
                                </div>
                             </div>
                                 
                      <?php endforeach;?>
                            
            </div>
                     
          </div>
          		<?php if($this->lastpage>1):?>
                 	<div class="paginationFrame"><center><?php echo $this->partial('index/pagination.phtml',array('lastpage'=>$this->lastpage,'pagenum'=>$this->pagenum));?></center></div>
                <?php endif;?>	
                
          <?php else:?>
        		<div class="result_label_anual">There are no matching events for <?php echo EventDisplay::$monthShortname[$this->month];?> <?php echo $this->year;?></div>
          <?php endif;?>	
		<!--==| END: Events |==-->
		
		</div>
</div><!-- End ajax div -->
